import Link from 'next/link';
import EditorialArtwork from '@/components/media/EditorialArtwork';
import { FactWheel, LayeredExplanation, StoryConstellation } from '@/components/visual/Infographics';
import styles from '@/styles/ContentPage.module.css';

const topics=[['Chúa Ba Ngôi','Một Thiên Chúa duy nhất trong Ba Ngôi Vị: Chúa Cha, Chúa Con và Chúa Thánh Thần','art.rublev-trinity'],['Mầu nhiệm Nhập Thể','Ngôi Lời vĩnh cửu thật sự trở nên người nơi Đức Giêsu Kitô','art.annunciation-fra-angelico'],['Bí tích Thánh Thể','Đức Kitô trao ban chính mình cho Giáo Hội trong bí tích Thánh Thể','art.last-supper-leonardo'],['Ân sủng','Hồng ân nhưng không của Thiên Chúa chữa lành và nâng con người lên','art.augustine-philippe-de-champaigne'],['Giáo Hội','Dân Thiên Chúa, Thân Thể Đức Kitô và Đền Thờ Chúa Thánh Thần','place.rome-st-peters'],['Sự Phục Sinh','Đức Kitô đã sống lại thật; Người là niềm hy vọng phục sinh của chúng ta','art.resurrection-christ']];

export default function DoctrinePage(){return <main className={styles.page}><div className="container">
<section className={styles.hero}><div className={styles.heroCopy}><div className="eyebrow">Khám phá Giáo lý · Thần học trực quan</div><h1 className={styles.title}>Đừng chỉ đọc giáo lý.<br/>Hãy nhìn thấy mối liên hệ.</h1><p className={styles.lead}>Mỗi mầu nhiệm được mở bằng một hình ảnh chính khi cần, rồi chuyển sang sơ đồ và mạng lưới. Hình nhỏ giúp nhận diện chủ đề mà không biến trang thành một gallery.</p></div><aside className={`${styles.darkPanel} ${styles.heroMedia}`}><EditorialArtwork assetId="art.rublev-trinity" height={370} radius={18} sizes="(max-width: 1024px) 100vw, 46vw" priority/><div className={styles.darkPanelCopy}><div className="eyebrow">Một hình ảnh · nhiều lớp hiểu</div><p>Nghệ thuật tạo điểm vào; sơ đồ giúp nhìn thấy tương quan; văn bản và nguồn làm rõ điều hình ảnh không thể nói hết.</p></div></aside></section>
<section className={`${styles.cardGrid} ${styles.section}`}>{topics.map(([title,body,asset],i)=><article key={title} className={`${styles.mediaCard} ${styles.topicCard}`}><EditorialArtwork assetId={asset} height={72} radius={11} showCredit={false} sizes="72px"/><div className={styles.cardCopy}><small style={{display:'block',fontWeight:800,color:'#94631d'}}>0{i+1}</small><h2 style={{font:'22px Georgia,serif',color:'#0b2848',margin:'5px 0'}}>{title}</h2><p style={{font:'12px/1.5 Georgia,serif',color:'#68717a',margin:'0 0 6px'}}>{body}</p><Link href="/hoi-dap" style={{fontSize:12}}>Khám phá chủ đề →</Link></div></article>)}</section>
<section className={`${styles.grid2} ${styles.sectionTight}`}><LayeredExplanation title="Chúa Ba Ngôi" layers={[{title:'Một Thiên Chúa',detail:'đức tin Công giáo tuyên xưng duy nhất một Thiên Chúa'},{title:'Ba Ngôi Vị',detail:'Chúa Cha, Chúa Con và Chúa Thánh Thần phân biệt thật sự'},{title:'Cùng một bản tính Thiên Chúa',detail:'không phải ba vị thần, nhưng một Thiên Chúa'},{title:'Tương quan',detail:'ngôn ngữ thần học diễn tả các Ngôi trong tương quan với nhau'}]}/><FactWheel center="Bí tích Thánh Thể" items={['Bữa Tiệc Ly','Hy tế Đức Kitô','Mình và Máu Chúa','Thánh lễ','Hiệp thông','Sứ mạng']}/></section>
<section className={styles.sectionTight}><StoryConstellation center="Mầu nhiệm Nhập Thể" centerAssetId="art.annunciation-fra-angelico" nodes={[{label:'Ngôi Lời',detail:'Con Thiên Chúa'},{label:'Đức Maria',detail:'Truyền Tin'},{label:'Đức Giêsu Kitô',detail:'Thiên Chúa thật & người thật'},{label:'Nixêa 325',detail:'Kitô học'},{label:'Kinh Thánh',detail:'Gioan 1'},{label:'Cứu độ',detail:'ý nghĩa'},{label:'Phụng vụ',detail:'Giáng Sinh'}]}/></section>
</div></main>}
