import Link from 'next/link';
import { FactWheel, RelationshipOrbit, VisualFlow } from '@/components/visual/Infographics';

const topics=[['Trinity','One God in three divine Persons','✥'],['Incarnation','The eternal Son truly becomes human','☩'],['Eucharist','Christ gives himself sacramentally to the Church','♕'],['Grace','God’s free gift that heals and elevates','◈'],['Church','The people of God, Body of Christ and temple of the Spirit','♜'],['Resurrection','Christ rises bodily, the pledge of our hope','✦']];

export default function DoctrinePage(){return <main style={{minHeight:'100vh',background:'#f5f0e6',padding:'clamp(28px,4vw,70px) 0'}}><div className="container">
  <section style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(320px,.85fr)',gap:'clamp(20px,3vw,44px)',alignItems:'stretch'}}><div><div className="eyebrow">Doctrine Explorer · Visual Theology</div><h1 style={{font:'clamp(54px,7vw,102px)/.9 Georgia,serif',letterSpacing:'-.05em',color:'#0b2848',margin:'12px 0 18px'}}>See how Catholic<br/>teaching connects.</h1><p style={{maxWidth:820,font:'clamp(16px,1.3vw,20px)/1.75 Georgia,serif',color:'#66717b'}}>Doctrine is not a list of disconnected definitions. Explore claims, Scripture, councils, theologians and sacramental life as a structured web of meaning.</p></div><aside><FactWheel center="One God" items={['Father','Son','Holy Spirit','One divine nature','Three Persons','Communion of love']}/></aside></section>

  <section style={{marginTop:24,display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:12}}>{topics.map(([title,body,icon])=><article key={title} style={{background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:16,padding:20}}><span style={{fontSize:30,color:'#b17d2d'}}>{icon}</span><h2 style={{font:'25px Georgia,serif',color:'#0b2848',margin:'10px 0 8px'}}>{title}</h2><p style={{font:'13px/1.65 Georgia,serif',color:'#68717a'}}>{body}</p><Link href="/ask" style={{fontSize:11,fontWeight:800}}>Explore explanation →</Link></article>)}</section>

  <section style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginTop:16}}><article style={{background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:18,padding:22}}><div className="eyebrow">How a doctrine is grounded</div><h2 style={{font:'32px Georgia,serif',color:'#0b2848'}}>Sources → interpretation → definition → worship</h2><VisualFlow steps={[{title:'Scripture',detail:'Biblical texts and patterns'},{title:'Tradition',detail:'Worship, Fathers and received teaching'},{title:'Councils',detail:'Authoritative clarification in controversy'},{title:'Church life',detail:'Doctrine expressed in prayer and sacrament'}]}/></article><article style={{background:'linear-gradient(135deg,#efe1c8,#fff8eb)',border:'1px solid #dbcbb3',borderRadius:18,padding:22}}><div className="eyebrow">Connected example</div><h2 style={{font:'32px Georgia,serif',color:'#0b2848'}}>Nicaea ↔ Trinity ↔ Incarnation</h2><RelationshipOrbit center="Nicene faith" items={[{label:'Nicaea 325',detail:'council'},{label:'Nicene Creed',detail:'confession'},{label:'Trinity',detail:'doctrine'},{label:'Christology',detail:'doctrine'},{label:'Athanasius',detail:'theologian'},{label:'Constantinople 381',detail:'council'}]}/><div style={{display:'grid',gap:8,marginTop:18}}><Link className="btn btn-primary" href="/councils/nicaea">Open Council of Nicaea →</Link><Link className="btn btn-secondary" href="/explore">Trace the graph →</Link></div></article></section>
</div></main>}
