'use client';

import { useState } from 'react';
import EditorialArtwork from '@/components/media/EditorialArtwork';

const stories=[['Ông Nôê và con tàu','Một câu chuyện về lòng tín thác, ơn cứu thoát và giao ước.','art.gutenberg-bible'],['Đavít và Gôliát','Can đảm lớn lên khi lòng tín thác mạnh hơn nỗi sợ.','art.gutenberg-bible'],['Người Samari nhân hậu','Chúa Giêsu dạy chúng ta ai thật sự là người thân cận.','art.gutenberg-bible'],['Thánh Augustinô','Một hành trình từ khắc khoải đến gặp gỡ Thiên Chúa.','art.augustine-philippe-de-champaigne']];
const quiz=[['Ai đã làm phép rửa cho Chúa Giêsu?',['Thánh Phêrô','Thánh Gioan Tẩy Giả','Thánh Phaolô'],1],['Chúa Giêsu sinh tại đâu?',['Bêlem','Rôma','Nadarét'],0],['Thân mẫu của Thánh Augustinô là ai?',['Thánh Monica','Thánh Clara','Thánh Têrêsa'],0]] as const;

export default function KidsPage(){const[index,setIndex]=useState(0);const[answer,setAnswer]=useState<number|null>(null);return <main style={{minHeight:'100vh',background:'linear-gradient(180deg,#fff8e8,#eef5f0)',padding:'clamp(24px,4vw,64px) 0'}}><div className="container">
<section style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(300px,.8fr)',gap:'clamp(20px,3vw,40px)',alignItems:'center'}}><div><div className="eyebrow">Thiếu nhi · Học qua câu chuyện</div><h1 style={{font:'clamp(50px,7vw,94px)/.92 Georgia,serif',letterSpacing:'-.05em',color:'#0b2848',margin:'12px 0 18px'}}>Chuyện lớn.<br/>Câu hỏi sáng.</h1><p style={{maxWidth:760,font:'clamp(17px,1.3vw,20px)/1.7 Georgia,serif',color:'#59656f'}}>Một cách đơn giản và vui hơn để trẻ khám phá Kinh Thánh, các Thánh và đời sống Giáo Hội qua câu chuyện ngắn, hình ảnh và câu đố nhẹ nhàng.</p></div><aside style={{borderRadius:28,background:'linear-gradient(145deg,#0c3155,#16476a)',padding:18,color:'#fff',overflow:'hidden'}}><EditorialArtwork assetId="art.gutenberg-bible" height={230} radius={18} showCredit={false}/><h2 style={{font:'34px Georgia,serif',margin:'16px 6px 8px'}}>Cuộc phiêu lưu hôm nay</h2><p style={{font:'15px/1.65 Georgia,serif',color:'#edf4f7',margin:'0 6px'}}>Theo chân Thánh Phêrô từ người đánh cá đến Tông đồ qua những chặng chuyện ngắn có hình minh họa.</p><button className="btn" style={{background:'#ffd97a',color:'#173451',margin:'14px 6px 4px'}}>Bắt đầu →</button></aside></section>
<section style={{marginTop:26}}><div className="eyebrow">Kệ truyện</div><h2 style={{font:'34px Georgia,serif',color:'#0b2848'}}>Chọn một câu chuyện</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12}}>{stories.map(([title,body,asset],i)=><article key={title} style={{background:i%2?'#eaf4f0':'#fff4db',border:'1px solid #ddd4bd',borderRadius:22,overflow:'hidden'}}><EditorialArtwork assetId={asset} height={150} radius={0} showCredit={false}/><div style={{padding:20}}><h3 style={{font:'26px Georgia,serif',color:'#0b2848',margin:'0 0 8px'}}>{title}</h3><p style={{font:'14px/1.6 Georgia,serif',color:'#59656f'}}>{body}</p><b style={{fontSize:12,color:'#7c5118'}}>Đọc truyện →</b></div></article>)}</div></section>
<section style={{display:'grid',gridTemplateColumns:'1fr .8fr',gap:16,marginTop:20}}><article style={{background:'#fffdf8',border:'1px solid #ded4c4',borderRadius:22,padding:24}}><div className="eyebrow">Câu đố nhỏ</div><h2 style={{font:'32px Georgia,serif',color:'#0b2848'}}>Câu {index+1}/{quiz.length}</h2><p style={{font:'22px Georgia,serif',color:'#172a40'}}>{quiz[index][0]}</p><div style={{display:'grid',gap:9}}>{quiz[index][1].map((choice,i)=><button key={choice} onClick={()=>setAnswer(i)} style={{textAlign:'left',border:'1px solid #d9ccb6',background:answer===i?(i===quiz[index][2]?'#dff1df':'#f5dfdf'):'#fffaf1',padding:13,borderRadius:12,cursor:'pointer',color:'#172a40'}}>{choice}</button>)}</div><div style={{display:'flex',justifyContent:'space-between',marginTop:16}}><button className="btn btn-secondary" onClick={()=>{setIndex(v=>Math.max(0,v-1));setAnswer(null)}} disabled={index===0}>← Trước</button><button className="btn btn-primary" onClick={()=>{setIndex(v=>Math.min(quiz.length-1,v+1));setAnswer(null)}} disabled={index===quiz.length-1}>Tiếp →</button></div></article><aside style={{background:'#0a2847',borderRadius:22,padding:24,color:'#fff'}}><div className="eyebrow">Dành cho gia đình</div><h2 style={{font:'30px Georgia,serif'}}>Học cùng nhau</h2><p style={{font:'15px/1.7 Georgia,serif',color:'#e6edf3'}}>Chế độ Thiếu nhi dùng lời giải thích ngắn, phù hợp lứa tuổi; phụ huynh vẫn có thể mở bài đầy đủ và nguồn tư liệu khi cần.</p><div style={{display:'grid',gap:8,marginTop:22}}>{['✓ Giải thích phù hợp lứa tuổi','✓ Không dùng khẳng định AI thiếu nguồn','✓ Có đường dẫn đến nguồn đầy đủ','✓ Ưu tiên tiếng Việt'].map(x=><div key={x} style={{padding:'10px 0',borderBottom:'1px solid rgba(255,255,255,.12)'}}>{x}</div>)}</div></aside></section>
</div></main>}
