'use client';

import { useState } from 'react';
import Link from 'next/link';
import EditorialArtwork from '@/components/media/EditorialArtwork';
import responsive from '@/styles/SecondaryPage.module.css';

const stories=[['Ông Nôê và con tàu','Một câu chuyện về lòng tín thác, ơn cứu thoát và giao ước.','art.gutenberg-bible','/kinh-thanh'],['Đavít và Gôliát','Can đảm lớn lên khi lòng tín thác mạnh hơn nỗi sợ.','art.gutenberg-bible','/kinh-thanh'],['Người Samari nhân hậu','Chúa Giêsu dạy chúng ta ai thật sự là người thân cận.','art.gutenberg-bible','/kinh-thanh'],['Thánh Augustinô','Một hành trình từ khắc khoải đến gặp gỡ Thiên Chúa.','art.augustine-philippe-de-champaigne','/cac-thanh/augustino-thanh-hippo']] as const;
const quiz=[['Ai đã làm phép rửa cho Chúa Giêsu?',['Thánh Phêrô','Thánh Gioan Tẩy Giả','Thánh Phaolô'],1],['Chúa Giêsu sinh tại đâu?',['Bêlem','Rôma','Nadarét'],0],['Thân mẫu của Thánh Augustinô là ai?',['Thánh Monica','Thánh Clara','Thánh Têrêsa'],0]] as const;

export default function KidsPage(){const[index,setIndex]=useState(0);const[answer,setAnswer]=useState<number|null>(null);const correct=answer!==null&&answer===quiz[index][2];return <main className={responsive.page} style={{minHeight:'100vh',background:'linear-gradient(180deg,#fff8e8,#eef5f0)',padding:'clamp(24px,4vw,64px) 0'}}><div className="container">
<section className={responsive.hero} style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,300px),1fr))',gap:'clamp(20px,3vw,40px)',alignItems:'center'}}><div><div className="eyebrow">Thiếu nhi · Học qua câu chuyện</div><h1 className={responsive.title} style={{font:'clamp(48px,7vw,94px)/.92 Georgia,serif',letterSpacing:'-.05em',color:'#0b2848',margin:'12px 0 18px'}}>Chuyện lớn.<br/>Câu hỏi sáng.</h1><p className={responsive.lead} style={{maxWidth:760,font:'clamp(18px,1.3vw,21px)/1.7 Georgia,serif',color:'#4d5b66'}}>Chọn một câu chuyện, xem hình, rồi thử một câu hỏi nhỏ. Hình ảnh được giữ gọn để trẻ dễ chọn và trang tải nhanh.</p></div><aside className={responsive.heroMedia} style={{borderRadius:28,background:'linear-gradient(145deg,#0c3155,#16476a)',padding:18,color:'#fff',overflow:'hidden'}}><EditorialArtwork assetId="art.gutenberg-bible" height={220} radius={18} showCredit={false} sizes="(max-width: 820px) 100vw, 46vw" priority/><h2 style={{font:'34px Georgia,serif',margin:'16px 6px 8px'}}>Cuộc phiêu lưu hôm nay</h2><p style={{font:'16px/1.65 Georgia,serif',color:'#edf4f7',margin:'0 6px'}}>Theo chân Chúa Giêsu và các Tông đồ qua hành trình có hình ảnh, từng chặng một.</p><div className={responsive.actions}><Link className="btn" href="/hanh-trinh/tu-chua-giesu-den-nixea" style={{display:'inline-block',background:'#ffd97a',color:'#173451',margin:'14px 6px 4px',minHeight:48,padding:'13px 18px'}}>Bắt đầu câu chuyện →</Link></div></aside></section>
<section style={{marginTop:30}}><div className="eyebrow">Kệ truyện</div><h2 style={{font:'36px Georgia,serif',color:'#0b2848'}}>Con muốn nghe chuyện nào?</h2><div className={responsive.grid} style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:12}}>{stories.map(([title,body,asset,route],i)=><Link className={responsive.storyCard} href={route} key={title} style={{display:'grid',gridTemplateColumns:'76px 1fr',gap:14,alignItems:'center',background:i%2?'#eaf4f0':'#fff4db',border:'1px solid #d4c7ad',borderRadius:22,color:'inherit',textDecoration:'none',padding:14,minHeight:128}}><EditorialArtwork assetId={asset} height={76} radius={12} showCredit={false} sizes="76px"/><div className={responsive.cardCopy}><small style={{fontWeight:900,color:'#81551b'}}>0{i+1}</small><h3 style={{font:'23px Georgia,serif',color:'#0b2848',margin:'5px 0'}}>{title}</h3><p style={{font:'14px/1.5 Georgia,serif',color:'#4d5b66',margin:'0 0 6px'}}>{body}</p><b style={{fontSize:13,color:'#704815'}}>Mở câu chuyện →</b></div></Link>)}</div></section>
<section className={responsive.grid} style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,320px),1fr))',gap:16,marginTop:22}}><article className={responsive.card} style={{background:'#fffdf8',border:'1px solid #ded4c4',borderRadius:22,padding:'clamp(18px,3vw,28px)'}}><div className="eyebrow">Câu đố nhỏ</div><h2 style={{font:'34px Georgia,serif',color:'#0b2848'}}>Câu {index+1}/{quiz.length}</h2><p style={{font:'24px/1.35 Georgia,serif',color:'#172a40'}}>{quiz[index][0]}</p><div style={{display:'grid',gap:10}}>{quiz[index][1].map((choice,i)=><button key={choice} onClick={()=>setAnswer(i)} aria-pressed={answer===i} style={{textAlign:'left',border:'2px solid #d3c2a5',background:answer===i?(i===quiz[index][2]?'#dff1df':'#f5dfdf'):'#fffaf1',padding:'15px 16px',minHeight:54,borderRadius:13,cursor:'pointer',color:'#172a40',fontSize:16,fontWeight:700}}>{choice}</button>)}</div>{answer!==null&&<p role="status" style={{font:'17px/1.5 Georgia,serif',fontWeight:700,color:correct?'#245c34':'#7a3e35',margin:'14px 0 0'}}>{correct?'Đúng rồi!':'Chưa đúng. Con thử lại nhé.'}</p>}<div className={responsive.quizActions} style={{display:'flex',justifyContent:'space-between',gap:10,marginTop:18}}><button className="btn btn-secondary" onClick={()=>{setIndex(v=>Math.max(0,v-1));setAnswer(null)}} disabled={index===0}>← Câu trước</button><button className="btn btn-primary" onClick={()=>{setIndex(v=>Math.min(quiz.length-1,v+1));setAnswer(null)}} disabled={index===quiz.length-1}>Câu tiếp →</button></div></article><aside className={responsive.card} style={{background:'#0a2847',borderRadius:22,padding:24,color:'#fff'}}><div className="eyebrow">Dành cho gia đình</div><h2 style={{font:'30px Georgia,serif'}}>Học cùng nhau</h2><p style={{font:'16px/1.7 Georgia,serif',color:'#e6edf3'}}>Trẻ thấy câu chuyện ngắn và câu hỏi đơn giản. Khi cần, cha mẹ có thể mở bài đầy đủ và nguồn tư liệu.</p><div style={{display:'grid',gap:8,marginTop:22}}>{['Câu chữ ngắn, dễ đọc','Nút lớn, dễ chạm','Phản hồi ngay sau câu trả lời','Có đường dẫn sang nội dung đầy đủ'].map(x=><div key={x} style={{padding:'11px 0',borderBottom:'1px solid rgba(255,255,255,.12)',fontSize:15}}>{x}</div>)}</div></aside></section>
</div></main>}
