'use client';
import Link from 'next/link';
import { useMemo, useState } from 'react';
import EditorialArtwork from '@/components/media/EditorialArtwork';
import { entities, relationships, sources } from '@/data/augustine';
import SourceBadge from '@/components/source/SourceBadge';
import { GeoStoryMap, MilestoneRibbon, StoryConstellation } from '@/components/visual/Infographics';
import { text } from '@/lib/knowledge/types';
import styles from './AugustineExplorer.module.css';
type Tab='Tổng quan'|'Dòng đời'|'Kết nối'|'Tác phẩm'|'Nguồn';
const timeline=[['354','Sinh tại Tagaste, Bắc Phi thuộc Rôma.'],['383','Rời Carthage đến Rôma và sau đó tới Milan.'],['387','Được Thánh Ambrôsiô làm phép Rửa tại Milan.'],['391','Được truyền chức linh mục tại Hippo.'],['395','Trở thành giám mục Hippo.'],['397','Bắt đầu viết Tự thuật (Confessions).'],['430','Qua đời trong thời Hippo bị vây hãm.']];
const entityArtwork:Record<string,string>={'person.monica':'person.monica-piero','person.ambrose-of-milan':'person.ambrose','place.hippo-regius':'place.hippo-regius','work.confessions':'work.confessions-manuscript'};
export default function AugustineExplorer(){const[tab,setTab]=useState<Tab>('Tổng quan');const augustine=entities.find(e=>e.id==='person.augustine-of-hippo');const connected=useMemo(()=>relationships.map(edge=>{const otherId=edge.from===augustine?.id?edge.to:edge.from;return{edge,entity:entities.find(item=>item.id===otherId)}}).filter(i=>i.entity),[augustine?.id]);const writings=connected.filter(i=>i.entity?.type==='work');if(!augustine)return null;return <main className={styles.page}>
<section className={`container ${styles.hero}`}><div className={styles.portraitPanel}><EditorialArtwork assetId="art.augustine-philippe-de-champaigne" height="100%" radius={22} objectPosition="center 20%"/><div className={styles.portraitMeta}><span>Thánh · Giám mục · Nhà thần học</span><span>354–430</span></div></div><div className={styles.identity}><div className="eyebrow">Thánh · Tiến sĩ Hội Thánh</div><h1>Thánh Augustinô thành Hippo</h1><p>Hãy nhìn cuộc đời Augustinô như một hành trình xuyên Địa Trung Hải và một mạng lưới con người, tác phẩm, Kinh Thánh và tư tưởng.</p><div className={styles.roles}><span>Tiến sĩ Hội Thánh</span><span>Giám mục Hippo</span><span>Bắc Phi</span><span>Hậu cổ đại</span></div><div className={styles.metrics}><div><strong>76</strong><span>năm cuộc đời</span></div><div><strong>{relationships.length}</strong><span>mối liên hệ</span></div><div><strong>{writings.length}</strong><span>tác phẩm nổi bật</span></div><div><strong>28/08</strong><span>lễ kính</span></div></div></div></section>
<nav className={`container ${styles.tabs}`}>{(['Tổng quan','Dòng đời','Kết nối','Tác phẩm','Nguồn'] as Tab[]).map(name=><button key={name} className={tab===name?styles.active:''} onClick={()=>setTab(name)}>{name}</button>)}</nav>
<section className={`container ${styles.body}`}>
{tab==='Tổng quan'&&<><article className={styles.storyPanel}><div className="eyebrow">Tiểu sử bằng không gian và thời gian</div><h2>Từ Tagaste đến Hippo: hành trình của một trái tim khắc khoải.</h2><GeoStoryMap points={[{label:'Tagaste',region:'sinh năm 354',x:47,y:25},{label:'Carthage',region:'học tập',x:48,y:27},{label:'Rôma',region:'383',x:48,y:18},{label:'Milan',region:'Ambrôsiô · 387',x:49,y:16,accent:true},{label:'Hippo',region:'giám mục · 395',x:46,y:24}]}/><MilestoneRibbon items={[{year:'354',title:'Tagaste',detail:'gia đình'},{year:'383',title:'Rôma & Milan',detail:'bước ngoặt trí thức'},{year:'387',title:'Phép Rửa',detail:'Thánh Ambrôsiô'},{year:'395',title:'Hippo',detail:'giám mục'},{year:'397+',title:'Trước tác',detail:'Tự thuật và thần học'}]}/></article><aside className={styles.legacy}><div className="eyebrow">Một người mở ra cả thế giới</div><h3>Bản đồ ảnh hưởng</h3><StoryConstellation center="Augustinô" centerAssetId="art.augustine-philippe-de-champaigne" nodes={[{label:'Thánh Monica',detail:'thân mẫu',assetId:'person.monica-piero'},{label:'Thánh Ambrôsiô',detail:'người làm phép Rửa',assetId:'person.ambrose'},{label:'Thánh Phaolô',detail:'ảnh hưởng Kinh Thánh',assetId:'person.paul'},{label:'Tự thuật',detail:'tác phẩm',assetId:'work.confessions-manuscript'},{label:'Ân sủng',detail:'thần học'},{label:'Hippo',detail:'địa danh',assetId:'place.hippo-regius'},{label:'Giáo Hội Tây phương',detail:'di sản'}]}/></aside></>}
{tab==='Dòng đời'&&<article className={styles.fullPanel}><div className="eyebrow">Dòng đời</div><h2>Bảy bước ngoặt</h2><MilestoneRibbon items={timeline.map(([year,detail])=>({year,title:detail.split('.')[0],detail}))}/></article>}
{tab==='Kết nối'&&<article className={styles.fullPanel}><div className="eyebrow">Đồ thị tri thức</div><h2>Con người, địa danh, tác phẩm và tư tưởng</h2><StoryConstellation center="Augustinô" centerAssetId="art.augustine-philippe-de-champaigne" nodes={connected.slice(0,7).map(({edge,entity})=>({label:entity?text(entity.labels):edge.type,detail:edge.type.replaceAll('_',' ').toLowerCase(),assetId:entity?entityArtwork[entity.id]:undefined}))}/></article>}
{tab==='Tác phẩm'&&<article className={styles.fullPanel}><div className="eyebrow">Tác phẩm nổi bật</div><h2>Các tác phẩm trong đồ thị</h2><div className={styles.books}>{writings.map(({entity})=>entity&&<div key={entity.id}>{entityArtwork[entity.id]?<EditorialArtwork assetId={entityArtwork[entity.id]} height={150} radius={10} showCredit={false}/>:null}<h3>{text(entity.labels)}</h3><p>{entity.subtype}</p><b>Mở tác phẩm →</b></div>)}</div></article>}
{tab==='Nguồn'&&<article className={styles.fullPanel}><div className="eyebrow">Nguồn gốc dữ liệu</div><h2>Bằng chứng phía sau hồ sơ</h2><p>Thực thể và mối quan hệ tham chiếu đến nguồn; hình ảnh biên tập tạo bối cảnh nhưng không được xem là bằng chứng lịch sử.</p><div style={{display:'flex',gap:10,flexWrap:'wrap',margin:'18px 0 24px'}}>{sources.map(source=><SourceBadge key={source.id} source={source}/>)}</div>{sources.map(source=><div className={styles.source} key={source.id}><a href={source.url} target="_blank" rel="noreferrer">{source.title} ↗</a><span>{source.publisher} · {source.sourceType} {source.license?`· ${source.license}`:''}</span></div>)}</article>}
</section><div className="container" style={{paddingBottom:30}}><Link className="btn btn-primary" href="/kham-pha">Mở bản đồ tri thức →</Link></div></main>}
