import Link from 'next/link';
import { MilestoneRibbon, RelationshipOrbit, VisualFlow } from '@/components/visual/Infographics';

const participants=[['Alexander of Alexandria','Bishop · defender of Nicene faith'],['Athanasius','Deacon · later bishop of Alexandria'],['Arius','Presbyter · central figure in controversy'],['Constantine','Roman emperor · convoked the council']];
const outcomes=[['Creed','A shared confession of the Son as true God from true God.'],['Homoousios','The Son is confessed as “of one substance” with the Father.'],['Canons','Disciplinary decisions addressed Church order and practice.'],['Legacy','The council became a defining reference point for later Trinitarian debates.']];

export default function NicaeaPage(){return <main style={{minHeight:'100vh',background:'#f5f0e6',padding:'clamp(28px,4vw,70px) 0'}}><div className="container">
  <section style={{display:'grid',gridTemplateColumns:'minmax(0,1.15fr) minmax(300px,.85fr)',gap:'clamp(18px,3vw,40px)',alignItems:'stretch'}}>
    <div style={{padding:'clamp(16px,2vw,28px) 0'}}><div className="eyebrow">Council Explorer · 325 · Nicaea</div><h1 style={{font:'clamp(52px,7vw,104px)/.9 Georgia,serif',letterSpacing:'-.05em',margin:'12px 0 18px',color:'#0b2848'}}>Council of<br/>Nicaea</h1><p style={{maxWidth:850,font:'clamp(16px,1.3vw,20px)/1.75 Georgia,serif',color:'#65707a'}}>Explore the controversy, people, theological language, decisions and long-term influence of the first ecumenical council as one connected historical system.</p><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:20}}>{['First Ecumenical Council','Christology','Nicene Creed','Roman Empire','325'].map(x=><span key={x} style={{border:'1px solid #d8c8ae',borderRadius:999,padding:'8px 11px',background:'#fffaf1',fontSize:11,fontWeight:700}}>{x}</span>)}</div></div>
    <aside style={{borderRadius:24,background:'linear-gradient(145deg,#0a2847,#061b32)',color:'#fff',padding:'clamp(22px,3vw,38px)',position:'relative',overflow:'hidden'}}><div style={{position:'absolute',width:340,height:340,border:'1px solid rgba(211,166,78,.45)',borderRadius:'50%',right:-110,top:-90,boxShadow:'0 0 0 45px rgba(255,255,255,.025),0 0 0 90px rgba(255,255,255,.015)'}}/><div className="eyebrow">The central question</div><h2 style={{font:'clamp(30px,3vw,48px)/1.04 Georgia,serif',margin:'18px 0',position:'relative'}}>Who is the Son in relation to the Father?</h2><p style={{font:'16px/1.7 Georgia,serif',color:'#d5dee7',position:'relative'}}>The council addressed a dispute over whether the Son was a creature or truly divine. Its answer shaped the language of the Nicene faith.</p><blockquote style={{borderLeft:'3px solid #d0a14d',margin:'28px 0 0',padding:'12px 0 12px 18px',font:'italic 17px/1.5 Georgia,serif',color:'#f0e4cc'}}>“true God from true God”</blockquote></aside>
  </section>

  <section style={{marginTop:24,background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:22,padding:'12px clamp(10px,2vw,26px)'}}><div className="eyebrow" style={{margin:'12px 0 0'}}>Historical arc</div><MilestoneRibbon items={[{year:'318',title:'Controversy',detail:'Dispute spreads from Alexandria'},{year:'325',title:'Council gathers',detail:'Bishops meet at Nicaea'},{year:'325',title:'Creed',detail:'Nicene formula is adopted'},{year:'330s',title:'Reception',detail:'Conflict and interpretation continue'},{year:'381',title:'Constantinople',detail:'Nicene faith is reaffirmed'}]}/></section>

  <section style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginTop:18}}><article style={{background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:18,padding:22}}><div className="eyebrow">People in the story</div><h2 style={{font:'32px Georgia,serif',color:'#0b2848'}}>Participants and voices</h2><RelationshipOrbit center="Nicaea 325" items={participants.map(([label,detail])=>({label,detail}))}/></article><article style={{background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:18,padding:22}}><div className="eyebrow">Council outcomes</div><h2 style={{font:'32px Georgia,serif',color:'#0b2848'}}>From controversy to legacy</h2><VisualFlow steps={outcomes.map(([title,detail])=>({title,detail}))}/></article></section>

  <section style={{marginTop:18,display:'grid',gridTemplateColumns:'1.15fr .85fr',gap:16}}><article style={{background:'#0a2847',color:'#fff',borderRadius:18,padding:24}}><div className="eyebrow">Visual doctrine link</div><h2 style={{font:'34px Georgia,serif'}}>The Nicene confession in one view</h2><VisualFlow steps={[{title:'Father',detail:'unbegotten source'},{title:'Son',detail:'begotten, not made'},{title:'Homoousios',detail:'of one substance'},{title:'Creed',detail:'shared confession of faith'}]}/></article><aside style={{background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:18,padding:22}}><div className="eyebrow">Continue exploring</div><h2 style={{font:'28px Georgia,serif',color:'#0b2848'}}>Connect this council to the wider atlas.</h2><div style={{display:'grid',gap:8}}><Link className="btn btn-primary" href="/timeline">Place Nicaea on the timeline →</Link><Link className="btn btn-secondary" href="/learn/jesus-to-nicaea">Learn Jesus → Nicaea →</Link><Link className="btn btn-secondary" href="/ask">Ask about the controversy →</Link></div></aside></section>
</div></main>}
