import Link from 'next/link';
import EditorialArtwork from '@/components/media/EditorialArtwork';
import { MilestoneRibbon, RelationshipOrbit, VisualFlow } from '@/components/visual/Infographics';

const participants=[['Alexandros thành Alexandria','Giám mục · bảo vệ đức tin Nixêa'],['Athanasiô','Phó tế · sau này là giám mục Alexandria'],['Ariô','Linh mục · nhân vật trung tâm của cuộc tranh luận'],['Constantinô','Hoàng đế Rôma · triệu tập công đồng']];
const outcomes=[['Kinh Tin Kính','Tuyên xưng Chúa Con là Thiên Chúa thật bởi Thiên Chúa thật.'],['Đồng bản thể','Chúa Con được tuyên xưng là “đồng bản thể” với Chúa Cha.'],['Các điều khoản kỷ luật','Các quyết định liên quan đến trật tự và đời sống Giáo Hội.'],['Di sản','Công đồng trở thành điểm quy chiếu quyết định cho các tranh luận về Chúa Ba Ngôi.']];

export default function NicaeaPage(){return <main style={{minHeight:'100vh',background:'#f5f0e6',padding:'clamp(28px,4vw,70px) 0'}}><div className="container">
  <section style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(320px,.9fr)',gap:'clamp(18px,3vw,40px)',alignItems:'stretch'}}>
    <div style={{padding:'clamp(16px,2vw,28px) 0'}}><div className="eyebrow">Khám phá Công đồng · 325 · Nixêa</div><h1 style={{font:'clamp(52px,7vw,104px)/.9 Georgia,serif',letterSpacing:'-.05em',margin:'12px 0 18px',color:'#0b2848'}}>Công đồng<br/>Nixêa</h1><p style={{maxWidth:850,font:'clamp(16px,1.3vw,20px)/1.75 Georgia,serif',color:'#59656f'}}>Khám phá cuộc tranh luận, các nhân vật, ngôn ngữ thần học, quyết định và ảnh hưởng lâu dài của công đồng đại kết đầu tiên như một hệ thống lịch sử được kết nối.</p><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:20}}>{['Công đồng đại kết đầu tiên','Kitô học','Kinh Tin Kính Nixêa','Đế quốc Rôma','Năm 325'].map(x=><span key={x} style={{border:'1px solid #d8c8ae',borderRadius:999,padding:'8px 11px',background:'#fffaf1',fontSize:11,fontWeight:700,color:'#173451'}}>{x}</span>)}</div></div>
    <aside style={{borderRadius:24,background:'#071d34',color:'#fff',padding:14,overflow:'hidden'}}><EditorialArtwork assetId="art.nicaea-icon" height={430} radius={18}/><div style={{padding:'18px 12px 10px'}}><div className="eyebrow">Câu hỏi trung tâm</div><h2 style={{font:'clamp(28px,3vw,44px)/1.04 Georgia,serif',margin:'12px 0'}}>Chúa Con là ai trong tương quan với Chúa Cha?</h2><p style={{font:'15px/1.7 Georgia,serif',color:'#e1e7ec'}}>Công đồng giải quyết tranh luận liệu Chúa Con chỉ là thụ tạo hay thật sự là Thiên Chúa. Câu trả lời của công đồng định hình ngôn ngữ đức tin Nixêa.</p></div></aside>
  </section>

  <section style={{marginTop:24,background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:22,padding:'12px clamp(10px,2vw,26px)'}}><div className="eyebrow" style={{margin:'12px 0 0'}}>Diễn tiến lịch sử</div><MilestoneRibbon items={[{year:'318',title:'Tranh luận',detail:'Bất đồng lan rộng từ Alexandria'},{year:'325',title:'Công đồng khai mạc',detail:'Các giám mục quy tụ tại Nixêa'},{year:'325',title:'Kinh Tin Kính',detail:'Công thức Nixêa được chấp nhận'},{year:'330s',title:'Tiếp nhận',detail:'Tranh luận và giải thích vẫn tiếp diễn'},{year:'381',title:'Constantinopolis',detail:'Đức tin Nixêa được tái khẳng định'}]}/></section>

  <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:16,marginTop:18}}><article style={{background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:18,padding:22}}><div className="eyebrow">Con người trong câu chuyện</div><h2 style={{font:'32px Georgia,serif',color:'#0b2848'}}>Nhân vật và tiếng nói</h2><RelationshipOrbit center="Nixêa 325" items={participants.map(([label,detail])=>({label,detail}))}/></article><article style={{background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:18,padding:22}}><div className="eyebrow">Kết quả công đồng</div><h2 style={{font:'32px Georgia,serif',color:'#0b2848'}}>Từ tranh luận đến di sản</h2><VisualFlow steps={outcomes.map(([title,detail])=>({title,detail}))}/></article></section>

  <section style={{marginTop:18,display:'grid',gridTemplateColumns:'1.15fr .85fr',gap:16}}><article style={{background:'#0a2847',color:'#fff',borderRadius:18,padding:24}}><div className="eyebrow">Kết nối giáo lý</div><h2 style={{font:'34px Georgia,serif'}}>Tuyên xưng Nixêa trong một sơ đồ</h2><VisualFlow steps={[{title:'Chúa Cha',detail:'nguồn không được sinh ra'},{title:'Chúa Con',detail:'được sinh ra, không phải được tạo thành'},{title:'Đồng bản thể',detail:'cùng một bản thể với Chúa Cha'},{title:'Kinh Tin Kính',detail:'lời tuyên xưng chung của Giáo Hội'}]}/></article><aside style={{background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:18,padding:22}}><EditorialArtwork assetId="art.rublev-trinity" height={180} radius={12} showCredit={false}/><div className="eyebrow" style={{marginTop:14}}>Tiếp tục khám phá</div><h2 style={{font:'28px Georgia,serif',color:'#0b2848'}}>Nối công đồng này với toàn bộ bản đồ tri thức.</h2><div style={{display:'grid',gap:8}}><Link className="btn btn-primary" href="/lich-su-giao-hoi">Đặt Nixêa vào dòng lịch sử →</Link><Link className="btn btn-secondary" href="/hanh-trinh/tu-chua-giesu-den-nixea">Học từ Chúa Giêsu đến Nixêa →</Link><Link className="btn btn-secondary" href="/hoi-dap">Hỏi về cuộc tranh luận →</Link></div></aside></section>
</div></main>}
