import Link from 'next/link';
import EditorialArtwork from '@/components/media/EditorialArtwork';
import { RelationshipOrbit, VisualFlow } from '@/components/visual/Infographics';

const readings=[['Bài đọc I','1 Côrintô 1,17–25','Đức Kitô chịu đóng đinh là sức mạnh và sự khôn ngoan của Thiên Chúa.'],['Đáp ca','Thánh vịnh 33','Trái đất đầy tràn tình thương của Chúa.'],['Tin Mừng','Mátthêu 25,1–13','Hãy tỉnh thức, vì anh em không biết ngày nào, giờ nào.']];
const prayers=[['Dâng ngày','Khởi đầu ngày mới bằng cách dâng công việc, niềm vui và những khó khăn cho Thiên Chúa.','art.resurrection-christ'],['Kinh Truyền Tin','Cầu nguyện với mầu nhiệm Ngôi Lời nhập thể.','art.annunciation-fra-angelico'],['Xét mình','Nhìn lại ngày sống trong tâm tình biết ơn, thành thật và hy vọng.','art.augustine-philippe-de-champaigne']];

export default function LiturgyPage(){return <main style={{minHeight:'100vh',background:'#f5f0e6',padding:'clamp(28px,4vw,70px) 0'}}><div className="container">
<section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,320px),1fr))',gap:'clamp(18px,3vw,40px)'}}><div><div className="eyebrow">Phụng vụ hằng ngày · Cầu nguyện & Lời Chúa</div><h1 style={{font:'clamp(48px,7vw,100px)/.9 Georgia,serif',letterSpacing:'-.05em',color:'#0a2847',margin:'12px 0 18px'}}>Bước vào đời sống Giáo Hội<br/>qua ngày hôm nay.</h1><p style={{maxWidth:820,font:'clamp(16px,1.3vw,20px)/1.75 Georgia,serif',color:'#59656f'}}>Ngày phụng vụ trở thành cánh cửa dẫn vào Kinh Thánh, các Thánh, mùa phụng vụ, giáo lý và đời sống cầu nguyện. Nội dung chính thức sẽ được lấy từ các nguồn phụng vụ đã được kiểm chứng.</p></div><aside style={{background:'#071d34',borderRadius:24,padding:14,color:'#fff'}}><EditorialArtwork assetId="art.mass-at-bolsena" height={390} radius={18}/><div style={{padding:'15px 10px 6px'}}><div className="eyebrow">Phụng vụ qua hình ảnh</div><p style={{font:'14px/1.65 Georgia,serif',color:'#e3e9ee'}}>Nghệ thuật lịch sử mở ra bối cảnh con người; các bài đọc, ngày lễ và nội dung giáo lý vẫn dựa trên dữ liệu và nguồn tư liệu có cấu trúc.</p></div></aside></section>
<section style={{marginTop:22,background:'linear-gradient(145deg,#0a2847,#071d34)',borderRadius:22,padding:'clamp(20px,2vw,30px)',color:'#fff'}}><div className="eyebrow">Nhịp chuyển của Thánh lễ</div><h2 style={{font:'clamp(28px,2.5vw,40px) Georgia,serif'}}>Từ quy tụ đến lên đường</h2><VisualFlow steps={[{title:'Quy tụ',detail:'cộng đoàn cùng hiện diện'},{title:'Phụng vụ Lời Chúa',detail:'Kinh Thánh được công bố'},{title:'Phụng vụ Thánh Thể',detail:'tạ ơn và hiệp thông'},{title:'Sai đi',detail:'được sai vào đời để sống Tin Mừng'}]}/></section>
<section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,320px),1fr))',gap:16,marginTop:22}}><article style={{background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:18,padding:22}}><div className="eyebrow">Các bài đọc trong Thánh lễ</div><h2 style={{font:'32px Georgia,serif',color:'#0b2848'}}>Lắng nghe Lời Chúa</h2><div style={{display:'grid',gap:10}}>{readings.map(([type,ref,body])=><div key={type} style={{display:'grid',gridTemplateColumns:'minmax(100px,120px) 1fr',gap:16,padding:15,border:'1px solid #e1d4c0',borderRadius:12,background:'#fffdf8'}}><div><small style={{display:'block',color:'#94631d',fontWeight:800,textTransform:'uppercase'}}>{type}</small><strong style={{display:'block',font:'16px Georgia,serif',marginTop:5,color:'#173451'}}>{ref}</strong></div><p style={{margin:0,font:'14px/1.6 Georgia,serif',color:'#59656f'}}>{body}</p></div>)}</div></article><aside style={{background:'linear-gradient(135deg,#efe1c8,#fff8eb)',border:'1px solid #dbcbb3',borderRadius:18,padding:22}}><EditorialArtwork assetId="art.gutenberg-bible" height={190} radius={12} showCredit={false}/><div className="eyebrow" style={{marginTop:14}}>Tri thức được kết nối</div><h2 style={{font:'29px Georgia,serif',color:'#0b2848'}}>Từ bài đọc bước vào bản đồ tri thức</h2><RelationshipOrbit center="Lời Chúa hôm nay" items={['Thánh Phaolô','Côrintô','Sự khôn ngoan của Thiên Chúa','Tỉnh thức','Nước Trời'].map(label=>({label}))}/></aside></section>
<section style={{marginTop:16,display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12}}>{prayers.map(([title,body,asset],i)=><article key={title} style={{background:i===1?'#0a2847':'#fffaf1',color:i===1?'#fff':'#0b2848',border:'1px solid #dfd1ba',borderRadius:16,overflow:'hidden'}}><EditorialArtwork assetId={asset} height={150} radius={0} showCredit={false}/><div style={{padding:20}}><h2 style={{font:'24px Georgia,serif',margin:'0 0 10px'}}>{title}</h2><p style={{font:'14px/1.65 Georgia,serif',color:i===1?'#e3e9ee':'#59656f'}}>{body}</p></div></article>)}</section>
<section style={{marginTop:16,background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:18,padding:22,display:'flex',justifyContent:'space-between',gap:18,alignItems:'center',flexWrap:'wrap'}}><div><div className="eyebrow">Tiếp tục</div><h2 style={{font:'29px Georgia,serif',color:'#0b2848',margin:'8px 0'}}>Từ phụng vụ đi sâu hơn vào sự hiểu biết.</h2></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Link className="btn btn-secondary" href="/kinh-thanh">Khám phá Kinh Thánh →</Link><Link className="btn btn-primary" href="/hoi-dap">Hỏi về các bài đọc hôm nay →</Link></div></section>
</div></main>}
