import Link from 'next/link';
import { RelationshipOrbit, VisualFlow } from '@/components/visual/Infographics';

const readings=[['First Reading','1 Corinthians 1:17–25','Christ crucified is the power and wisdom of God.'],['Psalm','Psalm 33','The earth is full of the goodness of the Lord.'],['Gospel','Matthew 25:1–13','Stay awake, for you know neither the day nor the hour.']];
const prayers=[['Morning Offering','Begin the day by offering work, joys and sufferings to God.'],['Angelus','Pray with the mystery of the Incarnation.'],['Examen','Review the day in gratitude, honesty and hope.']];

export default function LiturgyPage(){return <main style={{minHeight:'100vh',background:'#f5f0e6',padding:'clamp(28px,4vw,70px) 0'}}><div className="container">
<section style={{display:'grid',gridTemplateColumns:'minmax(0,1.1fr) minmax(300px,.9fr)',gap:'clamp(18px,3vw,40px)'}}><div><div className="eyebrow">Daily Liturgy · Prayer & Readings</div><h1 style={{font:'clamp(54px,7vw,100px)/.9 Georgia,serif',letterSpacing:'-.05em',color:'#0a2847',margin:'12px 0 18px'}}>Enter the Church<br/>through today.</h1><p style={{maxWidth:820,font:'clamp(16px,1.3vw,20px)/1.75 Georgia,serif',color:'#65707a'}}>The liturgical day becomes a doorway into Scripture, saints, seasons, doctrine and prayer. This screen is the product experience shell; production content will come from verified liturgical data sources.</p></div><aside style={{background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:24,padding:18}}><div className="eyebrow">Today as a knowledge hub</div><RelationshipOrbit center="Ordinary Time" items={[{label:'Readings',detail:'Word'},{label:'Saint',detail:'witness'},{label:'Prayer',detail:'response'},{label:'Season',detail:'calendar'},{label:'Doctrine',detail:'meaning'},{label:'Life',detail:'practice'}]}/></aside></section>

<section style={{marginTop:22,background:'linear-gradient(145deg,#0a2847,#071d34)',borderRadius:22,padding:'clamp(20px,2vw,30px)',color:'#fff'}}><div className="eyebrow">Liturgical movement</div><h2 style={{font:'clamp(28px,2.5vw,40px) Georgia,serif'}}>From gathering to mission</h2><VisualFlow steps={[{title:'Gather',detail:'the Church assembles'},{title:'Word',detail:'Scripture is proclaimed'},{title:'Eucharist',detail:'thanksgiving and communion'},{title:'Mission',detail:'sent to live the Gospel'}]}/></section>

<section style={{display:'grid',gridTemplateColumns:'1.25fr .75fr',gap:16,marginTop:22}}><article style={{background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:18,padding:22}}><div className="eyebrow">Mass readings</div><h2 style={{font:'32px Georgia,serif',color:'#0b2848'}}>Listen to the Word</h2><div style={{display:'grid',gap:10}}>{readings.map(([type,ref,body])=><div key={type} style={{display:'grid',gridTemplateColumns:'120px 1fr',gap:16,padding:15,border:'1px solid #e1d4c0',borderRadius:12,background:'#fffdf8'}}><div><small style={{display:'block',color:'#b17d2d',fontWeight:800,textTransform:'uppercase'}}>{type}</small><strong style={{display:'block',font:'16px Georgia,serif',marginTop:5}}>{ref}</strong></div><p style={{margin:0,font:'14px/1.6 Georgia,serif',color:'#68717a'}}>{body}</p></div>)}</div></article><aside style={{background:'linear-gradient(135deg,#efe1c8,#fff8eb)',border:'1px solid #dbcbb3',borderRadius:18,padding:22}}><div className="eyebrow">Connected knowledge</div><h2 style={{font:'29px Georgia,serif',color:'#0b2848'}}>From the readings into the atlas</h2><RelationshipOrbit center="Today’s Word" items={['Paul the Apostle','Corinth','Wisdom of God','Watchfulness','Kingdom of Heaven'].map(label=>({label}))}/></aside></section>

<section style={{marginTop:16,display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12}}>{prayers.map(([title,body],i)=><article key={title} style={{background:i===1?'#0a2847':'#fffaf1',color:i===1?'#fff':'#0b2848',border:'1px solid #dfd1ba',borderRadius:16,padding:20}}><span style={{fontSize:28,color:'#b98838'}}>♕</span><h2 style={{font:'24px Georgia,serif',margin:'10px 0'}}>{title}</h2><p style={{font:'13px/1.65 Georgia,serif',color:i===1?'#d4dce4':'#68717a'}}>{body}</p></article>)}</section>

<section style={{marginTop:16,background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:18,padding:22,display:'flex',justifyContent:'space-between',gap:18,alignItems:'center',flexWrap:'wrap'}}><div><div className="eyebrow">Continue</div><h2 style={{font:'29px Georgia,serif',color:'#0b2848',margin:'8px 0'}}>Move from worship into understanding.</h2></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Link className="btn btn-secondary" href="/scripture">Explore Scripture →</Link><Link className="btn btn-primary" href="/ask">Ask about today’s readings →</Link></div></section>
</div></main>}
