'use client';

import Link from 'next/link';
import EditorialArtwork from '@/components/media/EditorialArtwork';
import { RelationshipOrbit, VisualFlow } from '@/components/visual/Infographics';
import { useLocale } from '@/lib/i18n/LocaleProvider';
import styles from './home.module.css';

const viCategories = [
  ['art.nicaea-icon','Giáo Hội','Lịch sử, cơ cấu và sứ mạng','/lich-su-giao-hoi'],
  ['art.augustine-philippe-de-champaigne','Các Thánh','Cuộc đời, chứng tá và linh đạo','/cac-thanh/augustino-thanh-hippo'],
  ['art.gutenberg-bible','Kinh Thánh','Lời Chúa, nhân vật và bối cảnh','/kinh-thanh'],
  ['art.rublev-trinity','Giáo lý','Đức tin và các mầu nhiệm Kitô giáo','/giao-ly'],
  ['art.nicaea-icon','Các Công đồng','Những bước ngoặt trong lịch sử Giáo Hội','/cong-dong/nixea'],
  ['art.mass-at-bolsena','Phụng vụ','Thánh lễ, bí tích và đời sống cầu nguyện','/phung-vu'],
  ['art.mass-at-bolsena','Địa điểm','Thánh địa và những hành trình đức tin','/dia-diem'],
  ['art.augustine-philippe-de-champaigne','Bản đồ tri thức','Khám phá các mối liên hệ và nguồn tư liệu','/kham-pha'],
] as const;
const enCategories = [
  ['art.nicaea-icon','The Church','History, structure and mission','/timeline'],['art.augustine-philippe-de-champaigne','Saints','Lives of holiness and witness','/saints/augustine-of-hippo'],['art.gutenberg-bible','Scripture','Sacred Scripture and context','/scripture'],['art.rublev-trinity','Doctrine','Catholic teaching and mysteries','/doctrine'],['art.nicaea-icon','Councils','Ecumenical councils and history','/councils/nicaea'],['art.mass-at-bolsena','Liturgy','Mass, sacraments and prayer','/liturgy'],['art.mass-at-bolsena','Places','Holy sites and pilgrimage','/places'],['art.augustine-philippe-de-champaigne','Knowledge Map','Entities, relationships and sources','/explore'],
] as const;

export default function HomePage() {
  const { locale } = useLocale();
  const vi = locale === 'vi';
  const categories = vi ? viCategories : enCategories;
  const href = (viHref:string,enHref:string) => vi ? viHref : enHref;
  const rail = vi ? [['⌂  Trang chủ','/'],['☩  Từ Chúa Giêsu đến Nixêa','/hanh-trinh/tu-chua-giesu-den-nixea'],['♜  Lịch sử Giáo Hội','/lich-su-giao-hoi'],['▤  Kinh Thánh','/kinh-thanh'],['✦  Các Thánh','/cac-thanh/augustino-thanh-hippo'],['♟  Công đồng','/cong-dong/nixea'],['✥  Giáo lý','/giao-ly'],['♕  Phụng vụ','/phung-vu'],['⌖  Địa điểm','/dia-diem'],['◎  Bản đồ tri thức','/kham-pha'],['❉  Thiếu nhi','/thieu-nhi'],['✧  Hỏi đáp','/hoi-dap']] : [['⌂  Home','/'],['☩  Jesus to Nicaea','/learn/jesus-to-nicaea'],['♜  Church History','/timeline'],['▤  Scripture','/scripture'],['✦  Saints','/saints/augustine-of-hippo'],['♟  Councils','/councils/nicaea'],['✥  Doctrine','/doctrine'],['♕  Liturgy','/liturgy'],['⌖  Places','/places'],['◎  Knowledge Map','/explore'],['❉  Kids','/kids'],['✧  Ask','/ask']];
  return <main className={styles.page}><section className={styles.portal}>
    <aside className={styles.rail}><div className={styles.railBrand}><span className={styles.seal}>☩</span><strong>Catholic<br/>Knowledge</strong></div>{rail.map(([label,route],i)=><Link className={i===0?styles.railActive:styles.railLink} href={route} key={route}>{label}</Link>)}<blockquote>{vi?'“Lạy Chúa, Chúa đã dựng nên chúng con cho Chúa, và lòng chúng con khắc khoải cho đến khi được nghỉ yên trong Chúa.”':'“Our hearts are restless until they rest in You.”'}<small>— {vi?'Thánh Augustinô':'St. Augustine'}</small></blockquote></aside>
    <div className={styles.workspace}>
      <section className={styles.hero}>
        <div className={styles.heroCopy}><span className="eyebrow">{vi?'Bách khoa trực quan về đức tin Công giáo':'A visual encyclopedia of the Catholic faith'}</span><h1>Catholic<br/>Knowledge</h1><h2>{vi?'Khám phá. Hiểu biết. Lớn lên trong chân lý.':'Explore. Understand. Grow in Truth.'}</h2><p>{vi?'Một không gian trực quan và đáng tin cậy để khám phá đức tin, lịch sử và văn hóa Công giáo qua con người, địa danh, tác phẩm, giáo lý và các biến cố được kết nối với nhau.':'A visual and trustworthy guide to Catholic faith, history and culture, connected through people, places, writings, doctrine and events.'}</p><form className={styles.search} action={href('/kham-pha','/explore')}><input name="q" aria-label={vi?'Tìm kiếm Catholic Knowledge':'Search Catholic Knowledge'} placeholder={vi?'Bạn muốn tìm hiểu điều gì?':'What do you want to explore?'}/><button>{vi?'Tìm kiếm':'Search'}</button></form><div className={styles.popular}><b>{vi?'Khám phá nhanh:':'Popular:'}</b><Link href={href('/cac-thanh/augustino-thanh-hippo','/saints/augustine-of-hippo')}>{vi?'Thánh Augustinô':'St. Augustine'}</Link><Link href={href('/cong-dong/nixea','/councils/nicaea')}>{vi?'Công đồng Nixêa':'Council of Nicaea'}</Link><Link href={href('/giao-ly','/doctrine')}>{vi?'Chúa Ba Ngôi':'The Trinity'}</Link><Link href={href('/kinh-thanh','/scripture')}>{vi?'Kinh Thánh':'Scripture'}</Link></div></div>
        <div className={styles.heroArt}><EditorialArtwork assetId="art.augustine-philippe-de-champaigne" height={430} objectPosition="center 22%"/><blockquote>{vi?'“Lòng chúng con khắc khoải cho đến khi được nghỉ yên trong Chúa.”':'“Our hearts are restless until they rest in You.”'}<small>— {vi?'Thánh Augustinô':'St. Augustine'}</small></blockquote><Link href={href('/cac-thanh/augustino-thanh-hippo','/saints/augustine-of-hippo')}>{vi?'Khám phá cuộc đời ngài →':'Explore his story →'}</Link></div>
        <aside className={styles.today}><EditorialArtwork assetId="art.mass-at-bolsena" height={150} radius={14}/><div className={styles.todayTitle}><div><strong>{vi?'Hôm nay trong Giáo Hội':'Today in the Church'}</strong><small>29/08</small></div></div><h3>{vi?'Tưởng niệm cuộc Thương khó của Thánh Gioan Tẩy Giả':'Memorial of the Passion of Saint John the Baptist'}</h3><p>{vi?'Mùa Thường Niên · Ngày phụng vụ':'Ordinary Time · Liturgical day'}</p><Link className="btn btn-primary" href={href('/phung-vu','/liturgy')}>{vi?'Xem phụng vụ →':'View Full Liturgy →'}</Link></aside>
      </section>
      <section className={styles.categorySection}><div className={styles.sectionTitle}><h2>{vi?'Khám phá thế giới Công giáo':'Explore the Catholic World'}</h2><Link href={href('/kham-pha','/explore')}>{vi?'Mở bản đồ tri thức →':'Open knowledge map →'}</Link></div><div className={styles.categoryGrid}>{categories.map(([asset,title,body,route])=><Link href={route} className={styles.category} key={title}><div style={{width:76,flex:'0 0 76px'}}><EditorialArtwork assetId={asset} height={76} radius={12} showCredit={false}/></div><div><strong>{title}</strong><small>{body}</small><em>{vi?'Khám phá →':'Explore →'}</em></div></Link>)}</div></section>
      <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:12,marginTop:14}}><article style={{background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:16,padding:18}}><div className="eyebrow">{vi?'Tri thức được kết nối như thế nào':'How knowledge connects'}</div><h2 style={{font:'30px Georgia,serif',color:'#0b2848'}}>{vi?'Từ một nhân vật, mở ra cả một thế giới.':'One person opens into an entire world.'}</h2><RelationshipOrbit center={vi?'Augustinô':'Augustine'} items={[{label:'Monica',detail:vi?'thân mẫu':'person'},{label:'Ambrôsiô',detail:vi?'giám mục':'person'},{label:'Hippo',detail:vi?'địa danh':'place'},{label:'Confessions',detail:vi?'tác phẩm':'work'},{label:vi?'Ân sủng':'Grace',detail:vi?'giáo lý':'doctrine'}]}/></article><article style={{background:'linear-gradient(145deg,#0a2847,#071d34)',borderRadius:16,padding:18,color:'#fff'}}><div className="eyebrow">{vi?'Từ nguồn tư liệu đến sự hiểu biết':'From source to understanding'}</div><h2 style={{font:'30px Georgia,serif'}}>{vi?'Dữ kiện đáng tin cậy trở thành hành trình học trực quan.':'Evidence becomes a visual learning path.'}</h2><VisualFlow steps={vi?[{title:'Nguồn',detail:'tư liệu hoặc dữ liệu đáng tin cậy'},{title:'Dữ kiện',detail:'tri thức có cấu trúc'},{title:'Kết nối',detail:'nhân vật, nơi chốn và ý tưởng'},{title:'Giải thích',detail:'dòng thời gian, sơ đồ, hành trình hoặc AI'}]:[{title:'Source',detail:'trusted text or dataset'},{title:'Fact',detail:'structured canonical knowledge'},{title:'Graph',detail:'people, places and ideas connect'},{title:'Explain',detail:'timeline, diagram, journey or AI'}]}/></article></section>
      <section className={styles.dashboard}><article className={styles.featureCard}><div style={{width:150,float:'right',margin:'0 0 12px 16px'}}><EditorialArtwork assetId="art.augustine-philippe-de-champaigne" height={145} radius={14} showCredit={false}/></div><span className="eyebrow">{vi?'Nhân vật nổi bật · Thánh Augustinô thành Hippo':'Featured · St. Augustine of Hippo'}</span><h2>{vi?'Thánh Augustinô thành Hippo':'St. Augustine of Hippo'}</h2><p>{vi?'Giám mục, Tiến sĩ Hội Thánh và một trong những nhà tư tưởng có ảnh hưởng sâu rộng nhất trong truyền thống Kitô giáo.':'Bishop, Doctor of the Church, and one of the most influential thinkers in Christian tradition.'}</p><Link href={href('/cac-thanh/augustino-thanh-hippo','/saints/augustine-of-hippo')}>{vi?'Khám phá cuộc đời →':'Explore His Life →'}</Link></article><Link href={href('/hanh-trinh/tu-chua-giesu-den-nixea','/learn/jesus-to-nicaea')} className={styles.learnCard}><span className="eyebrow">{vi?'Hành trình học':'Learning Journey'}</span><h2>{vi?'Từ Chúa Giêsu đến Nixêa':'Jesus to Nicaea'}</h2><EditorialArtwork assetId="art.nicaea-icon" height={150} radius={12} showCredit={false}/><p>{vi?'Theo dòng 6 chặng quan trọng để hiểu sự hình thành của Giáo Hội sơ khai và Kinh Tin Kính.':'Follow the essential journey of our faith in 6 steps.'}</p><b>{vi?'Bắt đầu hành trình →':'Continue Journey →'}</b></Link></section>
    </div>
  </section></main>;
}
