'use client';
import Link from 'next/link';
import EditorialArtwork from '@/components/media/EditorialArtwork';
import { StoryConstellation } from '@/components/visual/Infographics';
import { useLocale } from '@/lib/i18n/LocaleProvider';
import styles from './home.module.css';
const viCategories=[['art.gutenberg-bible','Kinh Thánh','Sách, nhân vật, địa danh và chủ đề','/kinh-thanh'],['art.augustine-philippe-de-champaigne','Các Thánh','Cuộc đời, chứng tá và linh đạo','/cac-thanh/augustino-thanh-hippo'],['art.nicaea-icon','Lịch sử Giáo Hội','Biến cố, công đồng và bước ngoặt','/lich-su-giao-hoi'],['art.rublev-trinity','Giáo lý','Các mầu nhiệm và liên hệ thần học','/giao-ly'],['art.mass-at-bolsena','Phụng vụ','Thánh lễ, bí tích và cầu nguyện','/phung-vu'],['place.la-vang-shrine','Công giáo Việt Nam','La Vang, các Thánh Tử đạo và lịch sử','/dia-diem']] as const;
const enCategories=[['art.gutenberg-bible','Scripture','Books, people, places and themes','/scripture'],['art.augustine-philippe-de-champaigne','Saints','Lives, witness and spirituality','/saints/augustine-of-hippo'],['art.nicaea-icon','Church History','Events, councils and turning points','/timeline'],['art.rublev-trinity','Doctrine','Mysteries and theological connections','/doctrine'],['art.mass-at-bolsena','Liturgy','Mass, sacraments and prayer','/liturgy'],['place.la-vang-shrine','Catholic Vietnam','La Vang, martyrs and history','/places']] as const;
export default function HomePage(){const{locale}=useLocale();const vi=locale==='vi';const categories=vi?viCategories:enCategories;const href=(v:string,e:string)=>vi?v:e;return <main className={styles.page}>
<section className={styles.hero}><div className={styles.heroCopy}><span className="eyebrow">{vi?'Bách khoa trực quan về đức tin Công giáo':'A visual encyclopedia of the Catholic faith'}</span><h1>{vi?'Khám phá đức tin như một thế giới được kết nối.':'Explore the faith as a connected world.'}</h1><p>{vi?'Bắt đầu bằng một hình ảnh, nhìn thấy các mối liên hệ, rồi đi sâu vào câu chuyện và nguồn tư liệu.':'Begin with an image, see the connections, then go deeper into the story and its sources.'}</p><form className={styles.search} action={href('/kham-pha','/explore')}><input name="q" aria-label="Search" placeholder={vi?'Bạn muốn tìm hiểu điều gì?':'What do you want to explore?'}/><button>{vi?'Tìm kiếm':'Search'}</button></form></div><div className={styles.heroVisual}><EditorialArtwork assetId="art.augustine-philippe-de-champaigne" height={560} radius={26} objectPosition="center 20%"/><div className={styles.quoteCard}><blockquote>{vi?'“Lòng chúng con khắc khoải cho đến khi được nghỉ yên trong Chúa.”':'“Our hearts are restless until they rest in You.”'}</blockquote><span>— {vi?'Thánh Augustinô':'St. Augustine'}</span></div></div></section>
<section className={styles.todayStrip}><div><span className="eyebrow">{vi?'Hôm nay trong Giáo Hội':'Today in the Church'}</span><strong>{vi?'29 tháng 8 · Thánh Gioan Tẩy Giả bị trảm quyết':'29 August · Saint John the Baptist'}</strong><p>{vi?'Từ ngày phụng vụ, mở ra bài đọc, vị thánh, mùa phụng vụ và các mối liên hệ.':'Open readings, saint, season and related knowledge.'}</p></div><Link className="btn btn-primary" href={href('/phung-vu','/liturgy')}>{vi?'Khám phá hôm nay →':'Explore today →'}</Link></section>
<section className={styles.section}><div className={styles.sectionHead}><div><span className="eyebrow">{vi?'Một vũ trụ tri thức':'A knowledge universe'}</span><h2>{vi?'Mọi chủ đề đều có thể dẫn sang một chủ đề khác.':'Every topic can open another.'}</h2></div></div><StoryConstellation center={vi?'Đức tin Công giáo':'Catholic faith'} nodes={vi?[{label:'Kinh Thánh',detail:'Lời Chúa'},{label:'Các Thánh',detail:'chứng tá'},{label:'Giáo lý',detail:'mầu nhiệm'},{label:'Lịch sử',detail:'biến cố'},{label:'Phụng vụ',detail:'cử hành'},{label:'Địa danh',detail:'không gian'},{label:'Việt Nam',detail:'Giáo Hội địa phương'}]:[{label:'Scripture'},{label:'Saints'},{label:'Doctrine'},{label:'History'},{label:'Liturgy'},{label:'Places'},{label:'Vietnam'}]}/></section>
<section className={styles.section}><div className={styles.sectionHead}><div><span className="eyebrow">{vi?'Khám phá bằng hình ảnh':'Explore visually'}</span><h2>{vi?'Chọn một cánh cửa để bắt đầu':'Choose a doorway'}</h2></div></div><div className={styles.categoryGrid}>{categories.map(([asset,title,body,route])=><Link href={route} className={styles.category} key={title}><EditorialArtwork assetId={asset} height={190} radius={18} showCredit={false}/><div><h3>{title}</h3><p>{body}</p><span>{vi?'Mở chủ đề →':'Explore →'}</span></div></Link>)}</div></section>
<section className={styles.storyGrid}><article className={styles.featureStory}><div className={styles.storyImage}><EditorialArtwork assetId="place.la-vang-shrine" height={360} radius={22}/></div><div><span className="eyebrow">{vi?'Góc nhìn Việt Nam':'Vietnam lens'}</span><h2>{vi?'Đức Mẹ La Vang: từ một địa danh mở ra lịch sử Công giáo Việt Nam.':'Our Lady of La Vang opens Vietnamese Catholic history.'}</h2><p>{vi?'Địa danh → lịch sử → lòng tôn kính Đức Mẹ → Giáo Hội địa phương → các nhân vật và biến cố liên quan.':'Place → history → devotion → local Church → related people and events.'}</p><Link className="btn btn-secondary" href={href('/dia-diem','/places')}>{vi?'Khám phá La Vang →':'Explore La Vang →'}</Link></div></article><aside className={styles.graphCard}><span className="eyebrow">{vi?'Một người mở ra cả thế giới':'One person opens a world'}</span><h2>{vi?'Augustinô không chỉ là một trang tiểu sử.':'Augustine is more than a biography.'}</h2><StoryConstellation center={vi?'Augustinô':'Augustine'} nodes={[{label:'Monica',detail:vi?'thân mẫu':'mother'},{label:'Ambrôsiô',detail:vi?'phép Rửa':'baptism'},{label:'Hippo',detail:vi?'địa danh':'place'},{label:vi?'Tự thuật':'Confessions',detail:vi?'tác phẩm':'work'},{label:vi?'Ân sủng':'Grace',detail:vi?'thần học':'theology'}]}/></aside></section>
<section className={styles.journey}><div><span className="eyebrow">{vi?'Hành trình học hỏi':'Learning journey'}</span><h2>{vi?'Từ Chúa Giêsu đến Công đồng Nixêa':'From Jesus to Nicaea'}</h2><p>{vi?'Một hành trình điện ảnh nối con người, địa danh, biến cố và ý tưởng thay vì trình bày lịch sử như danh sách ngày tháng.':'A cinematic journey connecting people, places, events and ideas.'}</p><Link className="btn btn-primary" href={href('/hanh-trinh/tu-chua-giesu-den-nixea','/learn/jesus-to-nicaea')}>{vi?'Bắt đầu hành trình →':'Start journey →'}</Link></div><EditorialArtwork assetId="art.nicaea-icon" height={310} radius={22}/></section></main>}
