import Link from 'next/link';
import EditorialArtwork from '@/components/media/EditorialArtwork';
import { FactWheel, GeoStoryMap, MilestoneRibbon, StoryConstellation } from '@/components/visual/Infographics';
const books=[['Mátthêu','Đấng Mêsia và vị Thầy','place.jerusalem-holy-sepulchre'],['Máccô','Người Con đau khổ','art.resurrection-christ'],['Luca','Ơn cứu độ cho mọi dân','art.annunciation-fra-angelico'],['Gioan','Ngôi Lời trở nên người phàm','person.mary-theotokos'],['Công vụ','Chúa Thánh Thần và sứ mạng','person.peter'],['Rôma','Ân sủng và đức tin','person.paul']];
export default function ScripturePage(){return <main style={{minHeight:'100vh',background:'#f5f0e6',padding:'clamp(28px,4vw,70px) 0'}}><div className="container">
<section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,320px),1fr))',gap:'clamp(20px,3vw,42px)'}}><div><div className="eyebrow">Khám phá Kinh Thánh · Bản đồ trực quan</div><h1 style={{font:'clamp(48px,7vw,100px)/.91 Georgia,serif',letterSpacing:'-.05em',color:'#0a2847',margin:'12px 0 18px'}}>Đọc Kinh Thánh<br/>như bước vào một thế giới.</h1><p style={{maxWidth:820,font:'clamp(16px,1.3vw,20px)/1.75 Georgia,serif',color:'#59656f'}}>Nhân vật gặp nhau. Địa danh nối thành hành trình. Chủ đề vang lại qua nhiều sách. Nghệ thuật và infographic giúp nhìn thấy những liên hệ ấy mà không thay thế chính bản văn Kinh Thánh.</p></div><aside style={{background:'#071d34',borderRadius:24,padding:14,color:'#fff'}}><EditorialArtwork assetId="art.gutenberg-bible" height={360} radius={18} sizes="(max-width: 820px) 100vw, 46vw" priority/><div style={{padding:16}}><div className="eyebrow">Bản văn là trung tâm</div><p style={{font:'14px/1.65 Georgia,serif',color:'#e3e9ee'}}>Hình ảnh chính tạo bối cảnh; hình nhỏ chỉ giúp nhận diện sách, nhân vật hoặc địa danh mà không lấn át cấu trúc nội dung.</p></div></aside></section>
<section style={{marginTop:24}}><StoryConstellation center="Tin Mừng" nodes={[{label:'Chúa Giêsu',detail:'nhân vật trung tâm'},{label:'Đức Maria',detail:'Nadarét · Bêlem'},{label:'Thánh Phêrô',detail:'Tông đồ'},{label:'Thánh Phaolô',detail:'sứ mạng đến muôn dân'},{label:'Giêrusalem',detail:'Thương khó & Phục Sinh'},{label:'Nước Thiên Chúa',detail:'chủ đề'},{label:'Phục Sinh',detail:'biến cố'}]}/></section>
<section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,320px),1fr))',gap:16,marginTop:16}}><article style={{background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:20,padding:20}}><div className="eyebrow">Địa lý Kinh Thánh</div><h2 style={{font:'32px Georgia,serif',color:'#0b2848'}}>Từ Nadarét đến Rôma</h2><GeoStoryMap points={[{label:'Nadarét',region:'Galilê',x:56,y:23},{label:'Bêlem',region:'Giuđê',x:55,y:27},{label:'Giêrusalem',region:'Giuđê',x:57,y:28,accent:true},{label:'Antiôkia',region:'Syria',x:61,y:21},{label:'Rôma',region:'Ý',x:48,y:18}]}/></article><article style={{background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:20,padding:20}}><div className="eyebrow">Các chủ đề vang lại</div><h2 style={{font:'32px Georgia,serif',color:'#0b2848'}}>Một câu chuyện, nhiều lớp ý nghĩa</h2><FactWheel center="Tin Mừng" items={['Nước Thiên Chúa','Giao ước','Lòng thương xót','Môn đệ','Chúa Thánh Thần','Phục Sinh']}/></article></section>
<section style={{marginTop:16,background:'linear-gradient(135deg,#efe1c8,#fff8eb)',border:'1px solid #dbcbb3',borderRadius:18,padding:22}}><div className="eyebrow">Tin Mừng Luca như một hành trình</div><MilestoneRibbon items={[{year:'1–2',title:'Thời thơ ấu',detail:'Nadarét · Bêlem · Đức Maria'},{year:'3–9',title:'Galilê',detail:'giảng dạy và chữa lành'},{year:'9–19',title:'Lên đường',detail:'hướng về Giêrusalem'},{year:'20–23',title:'Giêrusalem',detail:'Thương khó và giáo huấn'},{year:'24',title:'Phục Sinh',detail:'mở sang Công vụ'}]}/></section>
<section style={{marginTop:16,display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10}}>{books.map(([name,body,asset],i)=><article key={name} style={{display:'grid',gridTemplateColumns:'76px 1fr',gap:14,alignItems:'center',background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:15,padding:12,minHeight:108}}><EditorialArtwork assetId={asset} height={76} radius={11} showCredit={false} sizes="76px"/><div><small style={{display:'block',color:'#94631d',fontWeight:800}}>0{i+1}</small><strong style={{display:'block',font:'21px Georgia,serif',color:'#102947',marginTop:3}}>{name}</strong><p style={{font:'12px/1.45 Georgia,serif',color:'#59656f',margin:'5px 0 0'}}>{body}</p></div></article>)}</section><div style={{marginTop:18}}><Link className="btn btn-primary" href="/kham-pha">Mở bản đồ tri thức →</Link></div>
</div></main>}
