import Link from 'next/link';
import EditorialArtwork from '@/components/media/EditorialArtwork';
import { MilestoneRibbon, RelationshipOrbit } from '@/components/visual/Infographics';

const books=[['Matthew','Gospel','Jesus as Messiah and teacher'],['Mark','Gospel','The suffering Son of God'],['Luke','Gospel','Salvation for all peoples'],['John','Gospel','The Word made flesh'],['Acts','History','The Spirit and apostolic mission'],['Romans','Letter','Grace, faith and life in Christ']];
const people=['Jesus','Mary','Peter','Paul','John the Baptist','The Twelve'];
const places=['Nazareth','Bethlehem','Jerusalem','Galilee','Antioch','Rome'];

export default function ScripturePage(){return <main style={{minHeight:'100vh',background:'#f5f0e6',padding:'clamp(28px,4vw,70px) 0'}}><div className="container">
  <section style={{display:'grid',gridTemplateColumns:'minmax(0,1.05fr) minmax(320px,.95fr)',gap:'clamp(20px,3vw,42px)',alignItems:'stretch'}}><div><div className="eyebrow">Scripture Explorer · Visual Bible Atlas</div><h1 style={{font:'clamp(54px,7vw,100px)/.91 Georgia,serif',letterSpacing:'-.05em',color:'#0a2847',margin:'12px 0 18px'}}>Read the Bible<br/>as a connected world.</h1><p style={{maxWidth:820,font:'clamp(16px,1.3vw,20px)/1.75 Georgia,serif',color:'#65707a'}}>Move between books, people, places, events and themes. The text remains primary; the knowledge graph helps you see context and relationships.</p><form style={{display:'flex',maxWidth:720,marginTop:22,border:'1px solid #d8cab3',borderRadius:12,overflow:'hidden',background:'#fffaf1'}} action="/scripture"><input aria-label="Search Scripture" placeholder="Search a book, person, place or theme…" style={{flex:1,border:0,padding:'15px 17px',background:'transparent',outline:0}}/><button style={{border:0,background:'#0a2847',color:'#fff',padding:'0 24px'}}>Search</button></form></div><aside style={{background:'#071d34',borderRadius:24,padding:14,color:'#fff'}}><EditorialArtwork assetId="art.gutenberg-bible" height={360} radius={18}/><div style={{padding:'16px 10px 6px'}}><div className="eyebrow">The Bible as material history</div><h2 style={{font:'30px Georgia,serif',margin:'8px 0'}}>Texts were copied, illuminated, carried and read.</h2><p style={{font:'14px/1.65 Georgia,serif',color:'#d5dee7'}}>Editorial artwork gives historical atmosphere; the structured graph still carries the actual facts and relationships.</p></div></aside></section>

  <section style={{marginTop:24,background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:18,padding:20}}><div className="eyebrow">Books</div><h2 style={{font:'32px Georgia,serif',color:'#0b2848'}}>Start with the New Testament</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10}}>{books.map(([name,type,body])=><article key={name} style={{padding:0,border:'1px solid #e1d4c0',borderRadius:12,background:'#fffdf8',overflow:'hidden'}}><EditorialArtwork assetId="art.gutenberg-bible" height={110} radius={0} showCredit={false}/><div style={{padding:15}}><h3 style={{font:'20px Georgia,serif',margin:'0 0 4px'}}>{name}</h3><small style={{color:'#b17d2d',fontWeight:800}}>{type}</small><p style={{font:'12px/1.55 Georgia,serif',color:'#68717a'}}>{body}</p></div></article>)}</div></section>

  <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:14,marginTop:16}}><article style={{background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:16,padding:20}}><div className="eyebrow">People</div><h2 style={{font:'27px Georgia,serif'}}>Who appears?</h2>{people.map(x=><div key={x} style={{padding:'9px 0',borderBottom:'1px solid #e4d8c5'}}>{x}</div>)}</article><article style={{background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:16,padding:20}}><div className="eyebrow">Places</div><h2 style={{font:'27px Georgia,serif'}}>Where does it happen?</h2>{places.map(x=><div key={x} style={{padding:'9px 0',borderBottom:'1px solid #e4d8c5'}}>{x}</div>)}</article><article style={{background:'#0a2847',color:'#fff',borderRadius:16,padding:20}}><div className="eyebrow">Themes</div><h2 style={{font:'27px Georgia,serif'}}>What connects the story?</h2>{['Kingdom of God','Covenant','Mercy','Discipleship','Holy Spirit','Resurrection'].map(x=><div key={x} style={{padding:'9px 0',borderBottom:'1px solid rgba(255,255,255,.12)'}}>{x}</div>)}</article></section>

  <section style={{marginTop:16,display:'grid',gridTemplateColumns:'1.2fr .8fr',gap:14}}><article style={{background:'linear-gradient(135deg,#efe1c8,#fff8eb)',border:'1px solid #dbcbb3',borderRadius:18,padding:22}}><div className="eyebrow">Visual reading path</div><h2 style={{font:'32px Georgia,serif',color:'#0b2848'}}>Luke as a narrative journey</h2><MilestoneRibbon items={[{year:'1–2',title:'Infancy',detail:'Nazareth, Bethlehem, Mary'},{year:'3–9',title:'Galilee',detail:'teaching and healing'},{year:'9–19',title:'Journey',detail:'toward Jerusalem'},{year:'20–23',title:'Jerusalem',detail:'Passion and teaching'},{year:'24',title:'Resurrection',detail:'opens into Acts'}]}/></article><aside style={{background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:18,padding:22}}><div className="eyebrow">Featured book · Luke</div><RelationshipOrbit center="Luke" items={[{label:'Jesus',detail:'central figure'},{label:'Mary',detail:'infancy narrative'},{label:'Jerusalem',detail:'destination'},{label:'Mercy',detail:'theme'},{label:'Resurrection',detail:'event'},{label:'Acts',detail:'sequel'}]}/><div style={{display:'grid',gap:8,marginTop:14}}><Link className="btn btn-primary" href="/explore">Open knowledge graph →</Link><Link className="btn btn-secondary" href="/ask">Ask about a passage →</Link></div></aside></section>
</div></main>}
