'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ReactFlow, Background, Controls, MiniMap, MarkerType, useReactFlow, ReactFlowProvider, type Edge, type Node, type NodeMouseHandler } from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { entities, relationships } from '@/data/augustine';
import { text } from '@/lib/knowledge/types';
import { buildExplorationIndex, findRelationshipPath } from '@/lib/knowledge/exploration';
import { toJourneyHref, type ExplorationContext } from '@/lib/knowledge/exploration-context';
import { getEditorialAsset } from '@/lib/media/assets';
import KnowledgeEntityNode, { type KnowledgeNodeData } from './KnowledgeEntityNode';
import AugustineContextSync from './AugustineContextSync';
import styles from './KnowledgeGraph.module.css';

type Lens = 'all' | 'person' | 'place' | 'work' | 'concept';
const positions: Record<string,{x:number;y:number}>={'person.augustine-of-hippo':{x:420,y:255},'person.monica':{x:65,y:80},'person.ambrose-of-milan':{x:760,y:80},'place.tagaste':{x:70,y:445},'place.hippo-regius':{x:760,y:455},'work.confessions':{x:230,y:580},'work.city-of-god':{x:530,y:600},'concept.grace':{x:850,y:270}};
const assets:Record<string,string>={'person.augustine-of-hippo':'art.augustine-philippe-de-champaigne','person.monica':'person.monica-piero','person.ambrose-of-milan':'person.ambrose','work.confessions':'art.gutenberg-bible','work.city-of-god':'art.gutenberg-bible'};
const nodeTypes={knowledge:KnowledgeEntityNode};
const index=buildExplorationIndex(entities,relationships);

function Canvas(){
 const [lens,setLens]=useState<Lens>('all'); const [query,setQuery]=useState(''); const [selectedId,setSelectedId]=useState('person.augustine-of-hippo'); const [pathOrigin,setPathOrigin]=useState<string|null>(null); const [history,setHistory]=useState<string[]>(['person.augustine-of-hippo']); const [journeyContext,setJourneyContext]=useState<ExplorationContext|null>(null); const {fitView}=useReactFlow();
 const selectedRelations=index.relationsByEntityId.get(selectedId)??[]; const neighbors=index.neighborIdsByEntityId.get(selectedId)??new Set([selectedId]);
 const activePath=useMemo(()=>pathOrigin?findRelationshipPath(pathOrigin,selectedId,relationships):[],[pathOrigin,selectedId]); const pathSet=useMemo(()=>new Set(activePath),[activePath]);
 const focus=useCallback((id:string)=>{if(!index.entityById.has(id))return;setSelectedId(id);setHistory(prev=>prev.at(-1)===id?prev:[...prev,id].slice(-7));requestAnimationFrame(()=>fitView({nodes:[{id}],duration:500,maxZoom:1.15,padding:.7}));},[fitView]);
 useEffect(()=>{const params=new URLSearchParams(window.location.search);const context:ExplorationContext={focusEntityId:params.get('focus')??undefined,journeyId:params.get('journey')??undefined,chapterId:params.get('chapter')??undefined,chapterLabel:params.get('chapterLabel')??undefined};if(context.journeyId)setJourneyContext(context);if(context.focusEntityId&&index.entityById.has(context.focusEntityId))focus(context.focusEntityId)},[focus]);
 const nodes=useMemo<Node<KnowledgeNodeData>[]>(()=>entities.map(entity=>{const visible=lens==='all'||entity.type===lens;const matches=!query||text(entity.labels).toLowerCase().includes(query.toLowerCase());const related=neighbors.has(entity.id)||pathSet.has(entity.id);return{id:entity.id,type:'knowledge',position:positions[entity.id]??{x:0,y:0},data:{label:text(entity.labels),type:entity.type,subtitle:entity.subtype,assetId:assets[entity.id],selected:entity.id===selectedId,muted:!(visible&&matches&&related),relationCount:(index.relationsByEntityId.get(entity.id)??[]).length,sourceCount:entity.sourceRefs.length,pathActive:pathSet.has(entity.id)}}}),[lens,query,selectedId,neighbors,pathSet]);
 const edges=useMemo<Edge[]>(()=>relationships.map(rel=>{const pathEdge=activePath.some((id,i)=>i<activePath.length-1&&((rel.from===id&&rel.to===activePath[i+1])||(rel.to===id&&rel.from===activePath[i+1])));const active=pathEdge||rel.from===selectedId||rel.to===selectedId;return{id:rel.id,source:rel.from,target:rel.to,label:rel.type.replaceAll('_',' ').toLowerCase(),animated:active,markerEnd:{type:MarkerType.ArrowClosed},style:{stroke:pathEdge?'#8b5d18':active?'#c99742':'#9da7ae',strokeWidth:pathEdge?3.5:active?2.6:1.2,opacity:active||neighbors.has(rel.from)&&neighbors.has(rel.to)?1:.15},labelStyle:{fontSize:10,fill:active?'#8a5b17':'#6f756f',fontWeight:active?700:400},labelBgStyle:{fill:'#fbf7ee',fillOpacity:.9}}}),[selectedId,neighbors,activePath]);
 const selected=index.entityById.get(selectedId)??entities[0]; const selectedAsset=assets[selected.id]?getEditorialAsset(assets[selected.id]):undefined; const handleNodeClick:NodeMouseHandler=(_,node)=>focus(node.id);
 return <div className={styles.shell}>
  {journeyContext&&<div className={styles.journeyBridge}><div><span>Đang khám phá từ Hành trình 01</span><b>{journeyContext.chapterLabel??'Từ Chúa Giêsu đến Nixêa'}</b><small>Explore giữ lại chương bạn vừa rời để bạn có thể quay lại đúng khoảnh khắc đó.</small></div><Link href={toJourneyHref(journeyContext)}>← Trở lại hành trình</Link></div>}
  <header className={styles.universeHeader}><div><div className="eyebrow">Catholic Knowledge · Explore mode</div><h1>Đi vào thế giới của Augustinô.</h1><p>Chọn một thực thể, theo dõi quan hệ của nó và giữ cùng ngữ cảnh trên graph, dòng thời gian và hành trình địa lý.</p></div><div className={styles.history}>{history.map((id,i)=>{const e=index.entityById.get(id);return e?<button onClick={()=>focus(id)} key={`${id}-${i}`}>{i>0&&'‹ '}{text(e.labels)}</button>:null})}</div></header>
  <div className={styles.toolbar}><input className={styles.search} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm Monica, Ambrôsiô, Tự Thuật…" aria-label="Tìm trong bản đồ"/>{([['all','Tất cả'],['person','Nhân vật'],['place','Địa danh'],['work','Tác phẩm'],['concept','Ý tưởng']] as [Lens,string][]).map(([v,l])=><button key={v} onClick={()=>setLens(v)} className={lens===v?styles.activeTool:''}>{l}</button>)}<button onClick={()=>{setPathOrigin(pathOrigin?null:selectedId)}} className={pathOrigin?styles.activeTool:''}>{pathOrigin?'Dừng nối đường':'Bắt đầu nối đường'}</button><button onClick={()=>fitView({duration:450,padding:.2})}>Toàn cảnh</button></div>
  {pathOrigin&&<div className={styles.pathReceipt}><span>Đang nối từ <b>{text(index.entityById.get(pathOrigin)?.labels??{vi:pathOrigin})}</b></span>{activePath.length>1&&<span>{activePath.map(id=>text(index.entityById.get(id)!.labels)).join(' → ')}</span>}</div>}
  <section className={styles.interactiveWorkspace}><div className={styles.interactiveCanvas}><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodeClick={handleNodeClick} fitView minZoom={.35} maxZoom={1.6} proOptions={{hideAttribution:true}} panOnScroll zoomOnPinch selectionOnDrag={false}><Background gap={32} size={1}/><Controls showInteractive={false}/><MiniMap pannable zoomable maskColor="rgba(6,24,45,.12)"/></ReactFlow><div className={styles.canvasHint}>Kéo để di chuyển · chọn node để tập trung · bật “nối đường” để truy vết quan hệ</div></div>
   <aside className={styles.entityInspector}>{selectedAsset&&<img className={styles.inspectorImage} src={selectedAsset.src} alt={selectedAsset.alt.vi??selectedAsset.alt.en}/>}<div className="eyebrow">{selected.type} · {selected.subtype}</div><h2>{text(selected.labels)}</h2>{selected.dates?.display&&<div className={styles.entityDates}>{text(selected.dates.display)}</div>}<p>{selected.summary?text(selected.summary):'Khám phá thực thể này qua các mối quan hệ được mô hình hóa trong bản đồ tri thức.'}</p><div className={styles.inspectorStats}><span>{selectedRelations.length} mối liên hệ</span><span>SRC {selected.sourceRefs.length}</span></div><div className={styles.relationActions}><strong>Đi tiếp từ đây</strong>{selectedRelations.map(rel=>{const otherId=rel.from===selectedId?rel.to:rel.from;const other=index.entityById.get(otherId);return other?<button key={rel.id} onClick={()=>focus(otherId)}><span>{rel.type.replaceAll('_',' ')}</span><b>{text(other.labels)} →</b></button>:null})}</div>{selectedAsset&&<div className={styles.assetEvidence}><span>Hình ảnh biên tập</span><a href={selectedAsset.sourceUrl} target="_blank" rel="noreferrer">{selectedAsset.creator} · {selectedAsset.license}</a></div>}<div className={styles.inspectorFoot}><strong>Explore, không phải slideshow.</strong><p>Mỗi lựa chọn giữ bạn trong cùng một không gian tri thức; nguồn và hình ảnh luôn có thể truy vết.</p></div></aside>
  </section><AugustineContextSync selectedId={selectedId} onFocus={focus}/>
 </div>;
}
export default function KnowledgeGraphExplorer(){return <ReactFlowProvider><Canvas/></ReactFlowProvider>}
