import Link from 'next/link';
import EditorialArtwork from '@/components/media/EditorialArtwork';
import { GeoStoryMap, MilestoneRibbon } from '@/components/visual/Infographics';

const places=[
  ['Jerusalem','Holy Land','Biblical city at the center of the Passion, Resurrection and early Church.','place.jerusalem-holy-sepulchre'],
  ['Rome','Italy','Apostolic memory, papacy, martyrs and the heart of the Latin Church.','place.rome-st-peters'],
  ['Lourdes','France','Marian pilgrimage associated with St. Bernadette and prayer for the sick.','art.mass-at-bolsena'],
  ['Fátima','Portugal','Marian apparitions and a global tradition of prayer and pilgrimage.','art.mass-at-bolsena'],
  ['La Vang','Vietnam','A major Vietnamese Marian pilgrimage site and national Catholic memory.','art.rublev-trinity'],
  ['Hippo Regius','North Africa','Augustine’s episcopal city and a key place in late-antique Christianity.','art.augustine-philippe-de-champaigne'],
];

export default function PlacesPage(){return <main style={{minHeight:'100vh',background:'#f5f0e6',padding:'clamp(28px,4vw,70px) 0'}}><div className="container">
<section style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(320px,1fr)',gap:'clamp(20px,3vw,42px)',alignItems:'stretch'}}><div><div className="eyebrow">Places & Pilgrimage · Catholic World Atlas</div><h1 style={{font:'clamp(54px,7vw,100px)/.9 Georgia,serif',letterSpacing:'-.05em',color:'#0a2847',margin:'12px 0 18px'}}>Faith has<br/>a geography.</h1><p style={{maxWidth:820,font:'clamp(16px,1.3vw,20px)/1.75 Georgia,serif',color:'#65707a'}}>Explore holy places through the people, events, writings and devotions connected to them—from Jerusalem and Rome to La Vang and the cities of the early Church.</p><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginTop:24}}><EditorialArtwork assetId="place.jerusalem-holy-sepulchre" height={210} radius={16}/><EditorialArtwork assetId="place.rome-st-peters" height={210} radius={16}/></div></div><GeoStoryMap points={[{label:'Fátima',region:'Portugal',x:43,y:18},{label:'Lourdes',region:'France',x:47,y:15},{label:'Rome',region:'Italy',x:51,y:19},{label:'Hippo',region:'North Africa',x:50,y:27},{label:'Jerusalem',region:'Holy Land',x:58,y:25},{label:'La Vang',region:'Vietnam',x:78,y:30,accent:true}]}/></section>
<section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:12,marginTop:24}}>{places.map(([name,region,body,asset],i)=><article key={name} style={{background:i===4?'linear-gradient(145deg,#0a2847,#071d34)':'#fffaf1',color:i===4?'#fff':'#0b2848',border:'1px solid #dfd1ba',borderRadius:18,overflow:'hidden',minHeight:330}}><EditorialArtwork assetId={asset} height={170} radius={0} showCredit={false}/><div style={{padding:20}}><small style={{display:'block',color:'#b17d2d',fontWeight:800,textTransform:'uppercase',letterSpacing:'.08em'}}>{region}</small><h2 style={{font:'28px Georgia,serif',margin:'7px 0'}}>{name}</h2><p style={{font:'13px/1.65 Georgia,serif',color:i===4?'#d1dbe4':'#68717a'}}>{body}</p><b style={{fontSize:11}}>Explore place →</b></div></article>)}</section>
<section style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginTop:16}}><article style={{background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:18,padding:22}}><div className="eyebrow">Pilgrimage journey</div><h2 style={{font:'32px Georgia,serif',color:'#0b2848'}}>Rome through the centuries</h2><MilestoneRibbon items={[{year:'64',title:'Peter & Paul',detail:'apostolic martyrdom'},{year:'2–3c',title:'Catacombs',detail:'memory of the martyrs'},{year:'4c',title:'Basilicas',detail:'imperial Christian Rome'},{year:'Medieval',title:'Pilgrimage',detail:'shrines and jubilees'},{year:'1962',title:'Vatican II',detail:'global council in Rome'}]}/></article><article style={{background:'linear-gradient(135deg,#efe1c8,#fff8eb)',border:'1px solid #dbcbb3',borderRadius:18,padding:22}}><div className="eyebrow">Vietnam lens</div><h2 style={{font:'32px Georgia,serif',color:'#0b2848'}}>La Vang as a local knowledge hub</h2><p style={{font:'14px/1.7 Georgia,serif',color:'#68717a'}}>Connect Vietnamese Catholic history, Marian devotion, pilgrimage, local Church memory and bilingual content through a place-centered view.</p><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:9,margin:'18px 0'}}>{['Vietnamese Catholic history','Marian devotion','Pilgrimage','Local memory'].map(x=><div key={x} style={{padding:12,border:'1px solid #d8c6a7',borderRadius:12,background:'#fffdf8',font:'12px Georgia,serif'}}>{x}</div>)}</div><Link className="btn btn-primary" href="/explore">Trace connected entities →</Link></article></section>
</div></main>}
