import Link from 'next/link';
import EditorialArtwork from '@/components/media/EditorialArtwork';
import { GeoStoryMap, MilestoneRibbon } from '@/components/visual/Infographics';

const places=[
  ['Giêrusalem','Thánh Địa','Thành phố Kinh Thánh ở trung tâm cuộc Thương khó, Phục Sinh và Giáo Hội sơ khai.','place.jerusalem-holy-sepulchre'],
  ['Rôma','Ý','Ký ức tông đồ, các vị tử đạo, giáo hoàng và trung tâm của Giáo Hội Latinh.','place.rome-st-peters'],
  ['Lộ Đức','Pháp','Địa điểm hành hương Đức Mẹ gắn với thánh Bernadette và lời cầu nguyện cho người đau yếu.','place.lourdes-sanctuary'],
  ['Fátima','Bồ Đào Nha','Địa điểm hành hương Đức Mẹ với truyền thống cầu nguyện mang tính toàn cầu.','place.fatima-sanctuary'],
  ['La Vang','Việt Nam','Trung tâm hành hương Đức Mẹ và một ký ức quan trọng của Công giáo Việt Nam.','place.la-vang-shrine'],
  ['Hippo Regius','Algérie','Thành giám mục của Thánh Augustinô; di tích tại Annaba còn giúp đặt đời ngài vào địa lý Bắc Phi Kitô giáo.','place.hippo-regius'],
  ['Nadarét','Thánh Địa','Thành phố gắn với biến cố Truyền Tin và đời sống ẩn dật của Chúa Giêsu.','place.nazareth-annunciation'],
];

export default function PlacesPage(){return <main style={{minHeight:'100vh',background:'#f5f0e6',padding:'clamp(28px,4vw,70px) 0'}}><div className="container">
<section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,360px),1fr))',gap:'clamp(20px,3vw,42px)',alignItems:'stretch'}}><div><div className="eyebrow">Địa điểm & Hành hương · Bản đồ Công giáo thế giới</div><h1 style={{font:'clamp(54px,7vw,100px)/.9 Georgia,serif',letterSpacing:'-.05em',color:'#0a2847',margin:'12px 0 18px'}}>Đức tin cũng có<br/>một địa lý.</h1><p style={{maxWidth:820,font:'clamp(16px,1.3vw,20px)/1.75 Georgia,serif',color:'#59656f'}}>Khám phá những nơi chốn thánh thiêng qua con người, biến cố, tác phẩm và lòng đạo gắn với chúng — từ Giêrusalem và Nadarét đến Hippo, Rôma, Lộ Đức, Fátima và La Vang.</p><div style={{marginTop:24,maxWidth:560}}><EditorialArtwork assetId="place.la-vang-shrine" height={260} radius={18} sizes="(max-width: 820px) 100vw, 42vw" priority/></div></div><GeoStoryMap points={[{label:'Fátima',region:'Bồ Đào Nha',x:43,y:18},{label:'Lộ Đức',region:'Pháp',x:47,y:15},{label:'Rôma',region:'Ý',x:51,y:19},{label:'Hippo',region:'Algérie',x:50,y:27},{label:'Giêrusalem',region:'Thánh Địa',x:58,y:25},{label:'Nadarét',region:'Thánh Địa',x:58,y:22},{label:'La Vang',region:'Việt Nam',x:78,y:30,accent:true}]}/></section>
<section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:12,marginTop:24}}>{places.map(([name,region,body,asset],i)=><article key={name} style={{display:'grid',gridTemplateColumns:'104px 1fr',gap:0,alignItems:'stretch',background:i===4?'linear-gradient(145deg,#0a2847,#071d34)':'#fffaf1',color:i===4?'#fff':'#0b2848',border:'1px solid #dfd1ba',borderRadius:18,overflow:'hidden',minHeight:170}}><EditorialArtwork assetId={asset} height="100%" radius={0} showCredit={false} sizes="104px"/><div style={{padding:18}}><small style={{display:'block',color:i===4?'#e2bb6c':'#94631d',fontWeight:800,textTransform:'uppercase',letterSpacing:'.08em'}}>{region}</small><h2 style={{font:'25px Georgia,serif',margin:'6px 0'}}>{name}</h2><p style={{font:'13px/1.55 Georgia,serif',color:i===4?'#e3e9ee':'#59656f',margin:'0 0 10px'}}>{body}</p><b style={{fontSize:11}}>{i===4?'Khám phá La Vang →':'Khám phá địa điểm →'}</b></div></article>)}</section>
<section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(100%,320px),1fr))',gap:16,marginTop:16}}><article style={{background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:18,padding:22}}><div className="eyebrow">Hành trình qua thời gian</div><h2 style={{font:'32px Georgia,serif',color:'#0b2848'}}>Rôma qua nhiều thế kỷ</h2><MilestoneRibbon items={[{year:'64',title:'Phêrô & Phaolô',detail:'ký ức tử đạo tông đồ'},{year:'Tk 2–3',title:'Hang toại đạo',detail:'ký ức các vị tử đạo'},{year:'Tk 4',title:'Các đại vương cung thánh đường',detail:'Rôma Kitô giáo thời đế quốc'},{year:'Trung cổ',title:'Hành hương',detail:'đền thánh và Năm Thánh'},{year:'1962',title:'Vaticanô II',detail:'công đồng toàn cầu tại Rôma'}]}/></article><article style={{background:'linear-gradient(135deg,#efe1c8,#fff8eb)',border:'1px solid #dbcbb3',borderRadius:18,padding:22}}><div className="eyebrow">Góc nhìn Việt Nam</div><h2 style={{font:'32px Georgia,serif',color:'#0b2848'}}>La Vang như một trung tâm tri thức địa phương</h2><p style={{font:'14px/1.7 Georgia,serif',color:'#59656f'}}>Kết nối lịch sử Công giáo Việt Nam, lòng sùng kính Đức Maria, hành hương và ký ức Giáo Hội địa phương qua một trang tập trung vào địa điểm.</p><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:9,margin:'18px 0'}}>{['Lịch sử Công giáo Việt Nam','Lòng sùng kính Đức Maria','Hành hương','Ký ức địa phương'].map(x=><div key={x} style={{padding:12,border:'1px solid #d8c6a7',borderRadius:12,background:'#fffdf8',font:'12px Georgia,serif',color:'#173451'}}>{x}</div>)}</div><Link className="btn btn-primary" href="/kham-pha">Theo dõi các thực thể liên quan →</Link></article></section>
</div></main>}
