import type { LocalizedText } from '@/lib/knowledge/types';

export type AssetRole = 'editorial' | 'portrait' | 'decorative' | 'factual-diagram' | 'manuscript';
export interface EditorialAsset { id:string; role:AssetRole; src:string; alt:LocalizedText; creator?:string; sourceUrl?:string; license?:string; attribution?:string; generated?:boolean; factual?:boolean; }
export const assetRules={factualDiagramsMustBeStructured:true,generatedRasterMayEncodeCanonicalFacts:false,requireAttributionWhenLicenseRequiresIt:true} as const;
export const editorialAssets:EditorialAsset[]=[
{id:'art.augustine-philippe-de-champaigne',role:'portrait',src:'https://commons.wikimedia.org/wiki/Special:FilePath/Saint%20Augustine%20by%20Philippe%20de%20Champaigne.jpg?width=1400',alt:{en:'Classical painted portrait of Saint Augustine',vi:'Chân dung hội họa cổ điển của Thánh Augustinô'},creator:'Philippe de Champaigne',sourceUrl:'https://commons.wikimedia.org/wiki/File:Saint_Augustine_by_Philippe_de_Champaigne.jpg',license:'Public domain',attribution:'Philippe de Champaigne · Wikimedia Commons',generated:false,factual:false},
{id:'person.monica-piero',role:'portrait',src:'https://commons.wikimedia.org/wiki/Special:FilePath/Piero%2C%20santa%20monaca.jpg?width=700',alt:{en:'Saint Monica, mother of Saint Augustine',vi:'Thánh Monica, thân mẫu của Thánh Augustinô'},creator:'Piero della Francesca',sourceUrl:'https://commons.wikimedia.org/wiki/File:Piero,_santa_monaca.jpg',license:'Public domain',attribution:'Piero della Francesca · Wikimedia Commons',generated:false,factual:false},
{id:'person.mary-theotokos',role:'portrait',src:'https://commons.wikimedia.org/wiki/Special:FilePath/Theotokos%20icon%2C%20Lebanon%20%2814th%20century%29.jpg?width=700',alt:{en:'Historic icon of Mary, the Theotokos',vi:'Biểu tượng cổ về Đức Maria, Mẹ Thiên Chúa'},creator:'Unknown iconographer',sourceUrl:'https://commons.wikimedia.org/wiki/File:Theotokos_icon,_Lebanon_(14th_century).jpg',license:'Public domain',attribution:'14th-century Theotokos icon · Wikimedia Commons',generated:false,factual:false},
{id:'person.ambrose',role:'portrait',src:'https://commons.wikimedia.org/wiki/Special:FilePath/St.%20Ambrose.jpg?width=700',alt:{en:'Historical painting of Saint Ambrose of Milan',vi:'Tranh lịch sử về Thánh Ambrôsiô thành Milan'},creator:'Historical artwork',sourceUrl:'https://commons.wikimedia.org/wiki/File:St._Ambrose.jpg',license:'Public domain',attribution:'Saint Ambrose · Wikimedia Commons',generated:false,factual:false},
{id:'person.peter',role:'portrait',src:'https://commons.wikimedia.org/wiki/Special:FilePath/Saint%20Peter.jpg?width=700',alt:{en:'Historical painting of Saint Peter the Apostle',vi:'Tranh lịch sử về Thánh Phêrô Tông đồ'},creator:'Attributed to Giovanni Lanfranco',sourceUrl:'https://commons.wikimedia.org/wiki/File:Saint_Peter.jpg',license:'Public domain',attribution:'Saint Peter · Wikimedia Commons',generated:false,factual:false},
{id:'person.paul',role:'portrait',src:'https://commons.wikimedia.org/wiki/Special:FilePath/Anonymous%20Saint%20Paul.jpg?width=700',alt:{en:'Historical painting of Saint Paul the Apostle',vi:'Tranh lịch sử về Thánh Phaolô Tông đồ'},creator:'Unknown artist',sourceUrl:'https://commons.wikimedia.org/wiki/File:Anonymous_Saint_Paul.jpg',license:'Public domain',attribution:'Saint Paul · Wikimedia Commons',generated:false,factual:false},
{id:'person.athanasius',role:'portrait',src:'https://commons.wikimedia.org/wiki/Special:FilePath/Athanasius%20I.jpg?width=700',alt:{en:'17th-century icon of Saint Athanasius of Alexandria',vi:'Biểu tượng thế kỷ XVII của Thánh Athanasiô thành Alexandria'},creator:'Unknown iconographer',sourceUrl:'https://commons.wikimedia.org/wiki/File:Athanasius_I.jpg',license:'Public domain',attribution:'Varna Archaeological Museum · Wikimedia Commons',generated:false,factual:false},
{id:'person.constantine',role:'portrait',src:'https://commons.wikimedia.org/wiki/Special:FilePath/Portrait%20of%20Constantine%20the%20Great.jpg?width=700',alt:{en:'Marble portrait of Constantine the Great, circa AD 315',vi:'Chân dung cẩm thạch của Hoàng đế Constantinô Đại đế, khoảng năm 315'},creator:'Roman sculptor, unknown',sourceUrl:'https://commons.wikimedia.org/wiki/File:Portrait_of_Constantine_the_Great.jpg',license:'Ancient public-domain artwork; photograph attribution on source page',attribution:'Wikimedia Commons',generated:false,factual:false},
{id:'art.nicaea-icon',role:'editorial',src:'https://commons.wikimedia.org/wiki/Special:FilePath/Nicaea%20icon.jpg?width=1200',alt:{en:'Historic icon depicting the First Council of Nicaea',vi:'Biểu tượng lịch sử về Công đồng Nixêa I'},creator:'Unknown iconographer',sourceUrl:'https://commons.wikimedia.org/wiki/File:Nicaea_icon.jpg',license:'Historical artwork; see Wikimedia Commons file page',attribution:'Wikimedia Commons',generated:false,factual:false},
{id:'work.confessions-manuscript',role:'manuscript',src:'https://commons.wikimedia.org/wiki/Special:FilePath/Basel%2C%20Universit%C3%A4tsbibliothek%2C%20A%20IV%204%2C%20f.%20145v%20%E2%80%93%20Aurelius%20Augustinus%2C%20Confessiones.JPG?width=700',alt:{en:'1471 manuscript page containing Augustine’s Confessions',vi:'Trang thủ bản năm 1471 chứa tác phẩm Tự Thuật của Thánh Augustinô'},creator:'Henricus de Bocholdia',sourceUrl:'https://commons.wikimedia.org/wiki/File:Basel,_Universit%C3%A4tsbibliothek,_A_IV_4,_f._145v_%E2%80%93_Aurelius_Augustinus,_Confessiones.JPG',license:'See Wikimedia Commons file page',attribution:'Universitätsbibliothek Basel · Wikimedia Commons',generated:false,factual:false},
{id:'art.gutenberg-bible',role:'editorial',src:'https://commons.wikimedia.org/wiki/Special:FilePath/Gutenberg%20bible.jpg?width=1200',alt:{en:'Illuminated page from the Gutenberg Bible',vi:'Trang Kinh Thánh Gutenberg được trang trí'},creator:'Johannes Gutenberg workshop',sourceUrl:'https://commons.wikimedia.org/wiki/File:Gutenberg_bible.jpg',license:'Public domain',attribution:'Gutenberg Bible · Wikimedia Commons',generated:false,factual:false},
{id:'art.rublev-trinity',role:'editorial',src:'https://commons.wikimedia.org/wiki/Special:FilePath/Rublev%20Troitsa.jpg?width=1200',alt:{en:'Andrei Rublev icon of the Holy Trinity',vi:'Biểu tượng Chúa Ba Ngôi của Andrei Rublev'},creator:'Andrei Rublev',sourceUrl:'https://commons.wikimedia.org/wiki/File:Rublev_Troitsa.jpg',license:'Public domain artwork',attribution:'Andrei Rublev · Wikimedia Commons',generated:false,factual:false},
{id:'art.mass-at-bolsena',role:'editorial',src:'https://commons.wikimedia.org/wiki/Special:FilePath/Raphael%20-%20The%20Mass%20at%20Bolsena.jpg?width=1400',alt:{en:'Raphael fresco of the Mass at Bolsena',vi:'Bích họa Thánh lễ tại Bolsena của Raphael'},creator:'Raphael',sourceUrl:'https://commons.wikimedia.org/wiki/File:Raphael_-_The_Mass_at_Bolsena.jpg',license:'Public domain',attribution:'Raphael · Wikimedia Commons',generated:false,factual:false},
{id:'place.rome-st-peters',role:'editorial',src:'https://commons.wikimedia.org/wiki/Special:FilePath/St.%20Peter%27s%20Basilica.jpg?width=1400',alt:{en:"St. Peter's Basilica in Vatican City",vi:'Vương cung thánh đường Thánh Phêrô tại Vatican'},creator:'Kai Pilger',sourceUrl:"https://commons.wikimedia.org/wiki/File:St._Peter%27s_Basilica.jpg",license:'Creative Commons Attribution-ShareAlike',attribution:'Kai Pilger · Wikimedia Commons',generated:false,factual:false},
{id:'place.jerusalem-holy-sepulchre',role:'editorial',src:'https://commons.wikimedia.org/wiki/Special:FilePath/Church%20of%20the%20Holy%20Sepulchre%20in%20Jerusalem.jpg?width=1400',alt:{en:'Church of the Holy Sepulchre in Jerusalem',vi:'Nhà thờ Mộ Thánh tại Giêrusalem'},creator:'David Shankbone',sourceUrl:'https://commons.wikimedia.org/wiki/File:Church_of_the_Holy_Sepulchre_in_Jerusalem.jpg',license:'Creative Commons; see source page',attribution:'David Shankbone · Wikimedia Commons',generated:false,factual:false},
{id:'place.lourdes-sanctuary',role:'editorial',src:'https://commons.wikimedia.org/wiki/Special:FilePath/Sanctuaire%20Notre-Dame%20de%20Lourdes.jpg?width=1400',alt:{en:'Sanctuary of Our Lady of Lourdes around 1897',vi:'Đền thánh Đức Mẹ Lộ Đức khoảng năm 1897'},creator:'Unknown photographer',sourceUrl:'https://commons.wikimedia.org/wiki/File:Sanctuaire_Notre-Dame_de_Lourdes.jpg',license:'Public domain',attribution:'1897 photograph · Bibliothèque nationale de France · Wikimedia Commons',generated:false,factual:false},
{id:'place.fatima-sanctuary',role:'editorial',src:'https://commons.wikimedia.org/wiki/Special:FilePath/Santu%C3%A1rio%20de%20F%C3%A1tima%20%2813708963163%29.jpg?width=1400',alt:{en:'Sanctuary of Our Lady of Fatima in Portugal',vi:'Đền thánh Đức Mẹ Fátima tại Bồ Đào Nha'},creator:'Terry Kearney',sourceUrl:'https://commons.wikimedia.org/wiki/File:Santu%C3%A1rio_de_F%C3%A1tima_(13708963163).jpg',license:'CC0 1.0',attribution:'Terry Kearney · Wikimedia Commons',generated:false,factual:false},
{id:'place.la-vang-shrine',role:'editorial',src:'https://commons.wikimedia.org/wiki/Special:FilePath/T%C6%B0%E1%BB%A3ng%20%C4%91%C3%A0i%20%C4%91%E1%BB%A9c%20M%E1%BA%B9%20La%20Vang%20%28to%C3%A0n%20c%E1%BA%A3nh%29.png?width=1400',alt:{en:'Our Lady of La Vang shrine in Quang Tri, Vietnam',vi:'Tượng đài Đức Mẹ La Vang tại Quảng Trị, Việt Nam'},creator:'Bùi Thụy Đào Nguyên',sourceUrl:'https://commons.wikimedia.org/wiki/File:T%C6%B0%E1%BB%A3ng_%C4%91%C3%A0i_%C4%91%E1%BB%A9c_M%E1%BA%B9_La_Vang_(to%C3%A0n_c%E1%BA%A3nh).png',license:'CC BY-SA 4.0',attribution:'Bùi Thụy Đào Nguyên · Wikimedia Commons',generated:false,factual:false},
{id:'motif.catholic-knowledge-seal',role:'decorative',src:'inline:brand-mark',alt:{en:'Catholic Knowledge cross and rays mark',vi:'Biểu tượng thánh giá và tia sáng Catholic Knowledge'},creator:'Catholic Knowledge',license:'Project asset',generated:false,factual:false},
{id:'diagram.knowledge-infographics',role:'factual-diagram',src:'component:Infographics',alt:{en:'Structured knowledge infographic',vi:'Đồ họa thông tin tri thức có cấu trúc'},creator:'Catholic Knowledge',license:'Project asset',generated:false,factual:true},
];
export function getEditorialAsset(id:string){return editorialAssets.find(asset=>asset.id===id)}
