'use client';

import { useState } from 'react';
import EditorialArtwork from '@/components/media/EditorialArtwork';
import { MilestoneRibbon, RelationshipOrbit } from '@/components/visual/Infographics';

const steps=[
 ['Chúa Giêsu và các Tông đồ','Câu chuyện bắt đầu với Chúa Giêsu, lời rao giảng Nước Thiên Chúa và những môn đệ trở thành chứng nhân của Người.','art.gutenberg-bible',['Chúa Giêsu','Nhóm Mười Hai','Galilê','Nước Thiên Chúa','Giêrusalem','Tin Mừng']],
 ['Lễ Ngũ Tuần','Các môn đệ công khai loan báo Tin Mừng; đời sống truyền giáo của Giáo Hội bắt đầu lan rộng.','art.gutenberg-bible',['Chúa Thánh Thần','Phêrô','Giêrusalem','Công vụ','Truyền giáo','Phép Rửa']],
 ['Phêrô, Phaolô và sứ mạng','Các cộng đoàn Kitô hữu lan rộng quanh Địa Trung Hải và đối diện những câu hỏi mục vụ mới.','art.gutenberg-bible',['Phêrô','Phaolô','Antiôkia','Rôma','Các thư','Dân ngoại']],
 ['Bách hại và tăng trưởng','Các vị tử đạo, các nhà hộ giáo và những cộng đoàn địa phương góp phần định hình căn tính Kitô giáo trong Đế quốc Rôma.','art.nicaea-icon',['Các vị tử đạo','Rôma','Hộ giáo','Giáo hội tại gia','Chứng tá','Đế quốc']],
 ['Constantinô và một thế giới đổi thay','Sự khoan dung tôn giáo của đế quốc làm thay đổi vị thế công khai của Giáo Hội và tạo điều kiện cho các công đồng lớn.','art.nicaea-icon',['Constantinô','Milan','Đế quốc','Giám mục','Phụng tự công khai','Công đồng']],
 ['Công đồng Nixêa','Năm 325, các giám mục quy tụ để giải quyết cuộc tranh luận Ariô và diễn tả rõ hơn đức tin của Giáo Hội về Đức Kitô.','art.nicaea-icon',['Nixêa','Ariô','Athanasiô','Kinh Tin Kính','Đồng bản thể','Kitô học']],
] as const;

export default function JesusToNicaeaPage(){const[active,setActive]=useState(0);const progress=((active+1)/steps.length)*100;return <main style={{background:'#f7f1e7',minHeight:'100vh',padding:'40px 0 80px'}}><div className="container">
 <div className="eyebrow">Hành trình học có hướng dẫn · Giáo Hội sơ khai</div><h1 style={{font:'clamp(50px,7vw,86px)/.94 Georgia,serif',letterSpacing:'-.04em',margin:'10px 0 14px',color:'#0b2848'}}>Từ Chúa Giêsu đến Nixêa</h1><p style={{maxWidth:760,color:'#59656f',font:'17px/1.7 Georgia,serif'}}>Sáu chặng trực quan kết nối con người, biến cố, địa danh và tư tưởng — thay vì biến lịch sử Giáo Hội thành một danh sách ngày tháng rời rạc.</p>
 <section style={{marginTop:22,background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:18,padding:'10px 16px'}}><MilestoneRibbon items={steps.map(([title],index)=>({year:`0${index+1}`,title,detail:index===active?'Chặng hiện tại':'Chặng hành trình'}))}/></section>
 <section style={{display:'grid',gridTemplateColumns:'280px minmax(0,1fr)',gap:16,marginTop:18}}>
  <nav style={{background:'#0a2847',borderRadius:16,padding:16,color:'#fff',boxShadow:'0 12px 30px rgba(20,33,58,.14)'}}>{steps.map(([title],index)=><button key={title} onClick={()=>setActive(index)} style={{width:'100%',display:'grid',gridTemplateColumns:'34px 1fr',gap:10,alignItems:'center',textAlign:'left',border:0,borderRadius:9,padding:'11px 10px',cursor:'pointer',background:active===index?'rgba(255,255,255,.13)':'transparent',color:'#fff',borderLeft:active===index?'3px solid #d1a04a':'3px solid transparent'}}><span style={{display:'grid',placeItems:'center',width:26,height:26,borderRadius:999,background:active===index?'#d1a04a':'rgba(255,255,255,.1)',color:'#071d34',fontWeight:800}}>{index+1}</span><span><small style={{display:'block',color:'#c2ccd5'}}>Chặng 0{index+1}</small><strong style={{font:'13px Georgia,serif'}}>{title}</strong></span></button>)}</nav>
  <article style={{minHeight:650,border:'1px solid #dfd1ba',borderRadius:16,background:'linear-gradient(135deg,#fffaf1,#f1e5d0)',padding:26,position:'relative',overflow:'hidden'}}><div style={{position:'relative',zIndex:2,display:'grid',gridTemplateColumns:'minmax(0,.9fr) minmax(320px,1.1fr)',gap:20,alignItems:'start'}}><div><div className="eyebrow">Chặng {active+1} · {active+1}/{steps.length}</div><EditorialArtwork assetId={steps[active][2]} height={260} radius={16} showCredit={false}/><h2 style={{font:'clamp(34px,4vw,48px)/1.02 Georgia,serif',color:'#0b2848',margin:'18px 0 16px'}}>{steps[active][0]}</h2><p style={{font:'17px/1.75 Georgia,serif',color:'#59656f'}}>{steps[active][1]}</p></div><RelationshipOrbit center={steps[active][0]} items={steps[active][3].map(label=>({label}))}/></div><div style={{position:'absolute',left:26,right:26,bottom:24}}><div style={{height:6,background:'#e1d5c3',borderRadius:99,overflow:'hidden'}}><div style={{width:`${progress}%`,height:'100%',background:'#9a691f',transition:'width .25s'}}/></div><div style={{display:'flex',justifyContent:'space-between',marginTop:14}}><button className="btn btn-secondary" disabled={active===0} onClick={()=>setActive(v=>Math.max(0,v-1))}>← Trước</button><button className="btn btn-primary" disabled={active===steps.length-1} onClick={()=>setActive(v=>Math.min(steps.length-1,v+1))}>Tiếp →</button></div></div></article>
 </section></div></main>}
