'use client';

import { useState } from 'react';
import { MilestoneRibbon, RelationshipOrbit } from '@/components/visual/Infographics';

const steps=[
 ['Jesus and the apostles','The story begins with Jesus, his proclamation of the Kingdom, and the disciples who become witnesses.','☩',['Jesus','The Twelve','Galilee','Kingdom of God','Jerusalem','Gospel']],
 ['Pentecost','The disciples proclaim the Gospel publicly and the Church’s missionary life accelerates.','✦',['Holy Spirit','Peter','Jerusalem','Acts','Mission','Baptism']],
 ['Peter, Paul and mission','Christian communities spread through the Mediterranean world and face new pastoral questions.','⌖',['Peter','Paul','Antioch','Rome','Letters','Gentile mission']],
 ['Persecution and growth','Martyrdom, apologetics and local communities shape Christian identity across the Roman Empire.','✧',['Martyrs','Rome','Apologists','House churches','Witness','Empire']],
 ['Constantine and a changing world','Imperial toleration changes the Church’s public situation and makes large councils possible.','♜',['Constantine','Milan','Empire','Bishops','Public worship','Council']],
 ['Council of Nicaea','Bishops gather in 325 to address the Arian controversy and articulate the Church’s confession of Christ.','♟',['Nicaea','Arius','Athanasius','Creed','Homoousios','Christology']],
] as const;

export default function JesusToNicaeaPage(){const[active,setActive]=useState(0);const progress=((active+1)/steps.length)*100;return <main style={{background:'#f7f1e7',minHeight:'100vh',padding:'40px 0 80px'}}><div className="container">
 <div className="eyebrow">Guided Learning Journey · Early Church</div><h1 style={{font:'clamp(50px,7vw,86px)/.94 Georgia,serif',letterSpacing:'-.04em',margin:'10px 0 14px',color:'#0b2848'}}>From Jesus to Nicaea</h1><p style={{maxWidth:760,color:'#69727b',font:'17px/1.7 Georgia,serif'}}>Six visual milestones connect people, events, places and ideas instead of treating Church history as isolated dates.</p>
 <section style={{marginTop:22,background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:18,padding:'10px 16px'}}><MilestoneRibbon items={steps.map(([title],index)=>({year:`0${index+1}`,title,detail:index===active?'Current step':'Journey step'}))}/></section>
 <section style={{display:'grid',gridTemplateColumns:'280px minmax(0,1fr)',gap:16,marginTop:18}}>
  <nav style={{background:'#0a2847',borderRadius:16,padding:16,color:'#fff',boxShadow:'0 12px 30px rgba(20,33,58,.14)'}}>{steps.map(([title,,icon],index)=><button key={title} onClick={()=>setActive(index)} style={{width:'100%',display:'grid',gridTemplateColumns:'34px 1fr',gap:10,alignItems:'center',textAlign:'left',border:0,borderRadius:9,padding:'11px 10px',cursor:'pointer',background:active===index?'rgba(255,255,255,.13)':'transparent',color:'#fff',borderLeft:active===index?'3px solid #d1a04a':'3px solid transparent'}}><span style={{fontSize:18,color:'#d9b267'}}>{icon}</span><span><small style={{display:'block',color:'#aebbc7'}}>0{index+1}</small><strong style={{font:'13px Georgia,serif'}}>{title}</strong></span></button>)}</nav>
  <article style={{minHeight:560,border:'1px solid #dfd1ba',borderRadius:16,background:'linear-gradient(135deg,#fffaf1,#f1e5d0)',padding:26,position:'relative',overflow:'hidden'}}><div style={{position:'absolute',right:-40,top:-40,width:240,height:240,border:'1px solid #d2a34f',borderRadius:'50%',boxShadow:'0 0 0 40px rgba(182,134,53,.07),0 0 0 80px rgba(182,134,53,.04)'}}/><div style={{position:'relative',zIndex:2,display:'grid',gridTemplateColumns:'minmax(0,.85fr) minmax(320px,1.15fr)',gap:20,alignItems:'center'}}><div><div className="eyebrow">Milestone {active+1} · Part {active+1} of {steps.length}</div><div style={{fontSize:72,color:'#b27f2e',margin:'20px 0 8px'}}>{steps[active][2]}</div><h2 style={{font:'clamp(34px,4vw,48px)/1.02 Georgia,serif',color:'#0b2848',margin:'0 0 16px'}}>{steps[active][0]}</h2><p style={{font:'17px/1.75 Georgia,serif',color:'#626d77'}}>{steps[active][1]}</p></div><RelationshipOrbit center={steps[active][0]} items={steps[active][3].map(label=>({label}))}/></div><div style={{position:'absolute',left:26,right:26,bottom:24}}><div style={{height:6,background:'#e1d5c3',borderRadius:99,overflow:'hidden'}}><div style={{width:`${progress}%`,height:'100%',background:'#b68435',transition:'width .25s'}}/></div><div style={{display:'flex',justifyContent:'space-between',marginTop:14}}><button className="btn btn-secondary" disabled={active===0} onClick={()=>setActive(v=>Math.max(0,v-1))}>← Previous</button><button className="btn btn-primary" disabled={active===steps.length-1} onClick={()=>setActive(v=>Math.min(steps.length-1,v+1))}>Next →</button></div></div></article>
 </section></div></main>}
