'use client';

import Link from 'next/link';
import { FormEvent,useState } from 'react';

const sample={question:'Why was the Council of Nicaea important?',answer:'Nicaea was important because bishops from across the Church gathered in 325 to address a major dispute about the identity of Christ. The council rejected the claim that the Son was a created being and confessed the Son as true God from true God, giving the Church a shared doctrinal formula that became foundational to the Nicene Creed.',evidence:[{title:'Council of Nicaea (325)',type:'Event',detail:'First ecumenical council; central to the Arian controversy.'},{title:'Nicene Creed',type:'Work',detail:'Creedal formula developed from the council’s confession of Christ.'},{title:'Arius and the Arian controversy',type:'Context',detail:'The theological dispute that precipitated the council.'}]};

export default function AskPage(){const[question,setQuestion]=useState(sample.question);const[submitted,setSubmitted]=useState(sample.question);function submit(e:FormEvent){e.preventDefault();setSubmitted(question.trim()||sample.question)}return <main style={{background:'#f7f1e7',minHeight:'100vh',padding:'42px 0 80px'}}><div className="container">
 <div className="eyebrow">Grounded Catholic Knowledge · Evidence First</div><h1 style={{font:'clamp(50px,7vw,86px)/.95 Georgia,serif',letterSpacing:'-.04em',margin:'10px 0 16px',color:'#0b2848'}}>Ask, then inspect<br/>the evidence.</h1><p style={{maxWidth:760,color:'#68717b',font:'17px/1.7 Georgia,serif'}}>The assistant explains canonical knowledge and points back to entities, relationships and sources. AI guides the exploration; it does not become the source of truth.</p>
 <form onSubmit={submit} style={{display:'flex',maxWidth:880,border:'1px solid #d9cab2',background:'#fffaf1',borderRadius:12,overflow:'hidden',margin:'24px 0 30px',boxShadow:'0 8px 22px rgba(48,35,18,.05)'}}><input value={question} onChange={e=>setQuestion(e.target.value)} aria-label="Ask Catholic Knowledge" style={{flex:1,border:0,background:'transparent',padding:'16px 18px',outline:0}}/><button style={{border:0,background:'#0a2847',color:'#fff',padding:'0 24px',fontWeight:800}}>Ask →</button></form>
 <section style={{display:'grid',gridTemplateColumns:'1.3fr .7fr',gap:16}}><article style={{background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:16,padding:24,boxShadow:'0 10px 28px rgba(48,35,18,.05)'}}><div className="eyebrow">Grounded explanation</div><h2 style={{font:'34px/1.15 Georgia,serif',color:'#0b2848',margin:'10px 0 14px'}}>{submitted}</h2><p style={{font:'17px/1.8 Georgia,serif',color:'#626d76'}}>{sample.answer}</p><div style={{borderTop:'1px solid #e2d6c3',marginTop:24,paddingTop:18}}><strong style={{font:'16px Georgia,serif'}}>Continue exploring</strong><div style={{display:'flex',gap:9,flexWrap:'wrap',marginTop:12}}><Link className="btn btn-secondary" href="/explore">Explore connections</Link><Link className="btn btn-secondary" href="/timeline">Open timeline</Link><Link className="btn btn-secondary" href="/learn/jesus-to-nicaea">Learn the story</Link></div></div></article>
 <aside style={{background:'linear-gradient(180deg,#0b2a4b,#081d35)',color:'#fff',borderRadius:16,padding:20,boxShadow:'0 12px 30px rgba(20,33,58,.14)'}}><div className="eyebrow">Evidence used</div><h2 style={{font:'27px Georgia,serif',margin:'9px 0 16px'}}>Grounding context</h2><div style={{display:'grid',gap:10}}>{sample.evidence.map(item=><div key={item.title} style={{border:'1px solid rgba(255,255,255,.14)',borderRadius:11,padding:13,background:'rgba(255,255,255,.05)'}}><div style={{color:'#d6aa56',fontSize:10,fontWeight:800,textTransform:'uppercase',letterSpacing:'.08em'}}>{item.type}</div><strong style={{display:'block',marginTop:5,font:'15px Georgia,serif'}}>{item.title}</strong><p style={{margin:'7px 0 0',color:'#c7d1dc',lineHeight:1.55,fontSize:12}}>{item.detail}</p></div>)}</div><div style={{marginTop:17,padding:13,borderRadius:10,background:'#f0e3cc',color:'#17314f',fontSize:11,lineHeight:1.55}}><strong>Source rule</strong><br/>Canonical sources produce facts. AI produces explanations from retrieved facts.</div></aside></section>
 </div></main>}
