'use client';

import Link from 'next/link';
import { FormEvent,useState } from 'react';
import EditorialArtwork from '@/components/media/EditorialArtwork';
import { RelationshipOrbit, VisualFlow } from '@/components/visual/Infographics';
import styles from '@/styles/ContentPage.module.css';

const sample={question:'Vì sao Công đồng Nixêa quan trọng?',answer:'Công đồng Nixêa quan trọng vì năm 325, các giám mục từ nhiều nơi trong Giáo Hội đã quy tụ để giải quyết một cuộc tranh luận lớn về căn tính của Đức Kitô. Công đồng bác bỏ quan điểm cho rằng Chúa Con chỉ là một thụ tạo và tuyên xưng Người là “Thiên Chúa thật bởi Thiên Chúa thật”. Công thức đức tin này trở thành nền tảng quan trọng của Kinh Tin Kính Nixêa.',evidence:[{title:'Công đồng Nixêa (325)',type:'Biến cố',detail:'Công đồng đại kết đầu tiên; trung tâm của cuộc tranh luận Ariô.'},{title:'Kinh Tin Kính Nixêa',type:'Văn kiện',detail:'Công thức tuyên xưng đức tin phát triển từ quyết định của công đồng.'},{title:'Ariô và cuộc tranh luận Ariô',type:'Bối cảnh',detail:'Tranh luận thần học thúc đẩy việc triệu tập công đồng.'}]};

export default function AskPage(){const[question,setQuestion]=useState(sample.question);const[submitted,setSubmitted]=useState(sample.question);function submit(e:FormEvent){e.preventDefault();setSubmitted(question.trim()||sample.question)}return <main className={`${styles.page} ${styles.pageWarm}`}><div className="container">
 <div className="eyebrow">Hỏi đáp Công giáo · Ưu tiên bằng chứng</div><section className={`${styles.hero} ${styles.heroCentered}`}><div className={styles.heroCopy}><h1 className={styles.title}>Hãy hỏi — rồi kiểm tra<br/>bằng chứng phía sau.</h1><p className={styles.lead}>Trợ lý giải thích tri thức đã được kiểm chứng và luôn dẫn người đọc trở lại thực thể, mối quan hệ và nguồn tư liệu. AI hỗ trợ việc khám phá; AI không thay thế nguồn sự thật.</p></div><div className={styles.heroMedia}><EditorialArtwork assetId="art.nicaea-icon" height={330} radius={22} sizes="(max-width: 1024px) 100vw, 46vw"/></div></section>
 <form onSubmit={submit} className={styles.askForm}><input value={question} onChange={e=>setQuestion(e.target.value)} aria-label="Hỏi Catholic Knowledge"/><button>Hỏi →</button></form>
 <section className={styles.card}><div className="eyebrow">Cách câu trả lời được kiểm chứng</div><VisualFlow steps={[{title:'Câu hỏi',detail:'người dùng hỏi bằng ngôn ngữ tự nhiên'},{title:'Truy xuất',detail:'thực thể, quan hệ và nguồn tư liệu'},{title:'Đối chiếu',detail:'kiểm chứng với tri thức chuẩn'},{title:'Giải thích',detail:'AI tạo câu trả lời dễ hiểu kèm bằng chứng'}]}/></section>
 <section className={`${styles.grid2} ${styles.sectionTight}`}><article className={styles.card}><div className="eyebrow">Giải thích dựa trên nguồn</div><h2 style={{font:'clamp(28px,4vw,34px)/1.15 Georgia,serif',color:'#0b2848',margin:'10px 0 14px',overflowWrap:'anywhere'}}>{submitted}</h2><p style={{font:'17px/1.8 Georgia,serif',color:'#59656f'}}>{sample.answer}</p><div style={{borderTop:'1px solid #e2d6c3',marginTop:24,paddingTop:18}}><strong style={{font:'16px Georgia,serif'}}>Tiếp tục khám phá</strong><div className={styles.actionRow}><Link className="btn btn-secondary" href="/kham-pha">Xem các mối liên hệ</Link><Link className="btn btn-secondary" href="/lich-su-giao-hoi">Mở dòng lịch sử</Link><Link className="btn btn-secondary" href="/hanh-trinh/tu-chua-giesu-den-nixea">Học theo hành trình</Link></div></div></article>
 <aside className={styles.card}><div className="eyebrow">Đồ thị bằng chứng</div><RelationshipOrbit center="Câu trả lời" items={[...sample.evidence.map(item=>({label:item.title,detail:item.type})),{label:'Kitô học',detail:'giáo lý'},{label:'325',detail:'năm'},{label:'Đức tin Nixêa',detail:'di sản'}]}/><div style={{marginTop:12,padding:13,borderRadius:10,background:'#0b2a4b',color:'#fff8e8',fontSize:11,lineHeight:1.55}}><strong style={{color:'#e2bb6c'}}>Nguyên tắc nguồn</strong><br/>Nguồn tư liệu tạo nên dữ kiện. AI tạo lời giải thích từ những dữ kiện đã được truy xuất.</div></aside></section>
 </div></main>}
