'use client';

import Link from 'next/link';
import { FormEvent,useState } from 'react';
import { RelationshipOrbit, VisualFlow } from '@/components/visual/Infographics';

const sample={question:'Why was the Council of Nicaea important?',answer:'Nicaea was important because bishops from across the Church gathered in 325 to address a major dispute about the identity of Christ. The council rejected the claim that the Son was a created being and confessed the Son as true God from true God, giving the Church a shared doctrinal formula that became foundational to the Nicene Creed.',evidence:[{title:'Council of Nicaea (325)',type:'Event',detail:'First ecumenical council; central to the Arian controversy.'},{title:'Nicene Creed',type:'Work',detail:'Creedal formula developed from the council’s confession of Christ.'},{title:'Arius and the Arian controversy',type:'Context',detail:'The theological dispute that precipitated the council.'}]};

export default function AskPage(){const[question,setQuestion]=useState(sample.question);const[submitted,setSubmitted]=useState(sample.question);function submit(e:FormEvent){e.preventDefault();setSubmitted(question.trim()||sample.question)}return <main style={{background:'#f7f1e7',minHeight:'100vh',padding:'42px 0 80px'}}><div className="container">
 <div className="eyebrow">Grounded Catholic Knowledge · Evidence First</div><h1 style={{font:'clamp(50px,7vw,86px)/.95 Georgia,serif',letterSpacing:'-.04em',margin:'10px 0 16px',color:'#0b2848'}}>Ask, then inspect<br/>the evidence.</h1><p style={{maxWidth:760,color:'#68717b',font:'17px/1.7 Georgia,serif'}}>The assistant explains canonical knowledge and points back to entities, relationships and sources. AI guides the exploration; it does not become the source of truth.</p>
 <form onSubmit={submit} style={{display:'flex',maxWidth:880,border:'1px solid #d9cab2',background:'#fffaf1',borderRadius:12,overflow:'hidden',margin:'24px 0 20px',boxShadow:'0 8px 22px rgba(48,35,18,.05)'}}><input value={question} onChange={e=>setQuestion(e.target.value)} aria-label="Ask Catholic Knowledge" style={{flex:1,border:0,background:'transparent',padding:'16px 18px',outline:0}}/><button style={{border:0,background:'#0a2847',color:'#fff',padding:'0 24px',fontWeight:800}}>Ask →</button></form>
 <section style={{background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:18,padding:18,marginBottom:16}}><div className="eyebrow">How grounding works</div><VisualFlow steps={[{title:'Question',detail:'user asks in natural language'},{title:'Retrieve',detail:'entities, relations and source records'},{title:'Verify',detail:'ground claims against canonical knowledge'},{title:'Explain',detail:'AI creates a readable answer with evidence'}]}/></section>
 <section style={{display:'grid',gridTemplateColumns:'1.15fr .85fr',gap:16}}><article style={{background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:16,padding:24,boxShadow:'0 10px 28px rgba(48,35,18,.05)'}}><div className="eyebrow">Grounded explanation</div><h2 style={{font:'34px/1.15 Georgia,serif',color:'#0b2848',margin:'10px 0 14px'}}>{submitted}</h2><p style={{font:'17px/1.8 Georgia,serif',color:'#626d76'}}>{sample.answer}</p><div style={{borderTop:'1px solid #e2d6c3',marginTop:24,paddingTop:18}}><strong style={{font:'16px Georgia,serif'}}>Continue exploring</strong><div style={{display:'flex',gap:9,flexWrap:'wrap',marginTop:12}}><Link className="btn btn-secondary" href="/explore">Explore connections</Link><Link className="btn btn-secondary" href="/timeline">Open timeline</Link><Link className="btn btn-secondary" href="/learn/jesus-to-nicaea">Learn the story</Link></div></div></article>
 <aside style={{background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:16,padding:18}}><div className="eyebrow">Evidence graph</div><RelationshipOrbit center="Answer" items={[...sample.evidence.map(item=>({label:item.title,detail:item.type})),{label:'Christology',detail:'doctrine'},{label:'325',detail:'date'},{label:'Nicene faith',detail:'legacy'}]}/><div style={{marginTop:12,padding:13,borderRadius:10,background:'#0b2a4b',color:'#fff',fontSize:11,lineHeight:1.55}}><strong style={{color:'#d6aa56'}}>Source rule</strong><br/>Canonical sources produce facts. AI produces explanations from retrieved facts.</div></aside></section>
 </div></main>}
