import Link from 'next/link';
import EditorialArtwork from '@/components/media/EditorialArtwork';
import { MilestoneRibbon } from '@/components/visual/Infographics';
import responsive from '@/styles/SecondaryPage.module.css';

const milestones=[
 {year:'30–60',title:'Giáo Hội thời các Tông đồ',era:'Khởi nguyên',body:'Các cộng đoàn Kitô hữu đầu tiên hình thành quanh lời chứng về Chúa Giêsu, lời giảng của các Tông đồ, cầu nguyện và việc bẻ bánh.'},
 {year:'325',title:'Công đồng Nixêa',era:'Giáo Hội thời Đế quốc',body:'Các giám mục quy tụ tại Nixêa để giải quyết cuộc tranh luận về căn tính của Đức Kitô và tuyên xưng Người là Thiên Chúa thật bởi Thiên Chúa thật.'},
 {year:'1054',title:'Rạn nứt Đông–Tây',era:'Trung cổ',body:'Những căng thẳng lâu dài về thần học, chính trị và Giáo Hội học dẫn đến sự phân ly sâu sắc giữa Rôma và Constantinopolis.'},
 {year:'1545',title:'Công đồng Trentô',era:'Thời Cải cách',body:'Giáo Hội Công giáo đáp lại phong trào Cải cách bằng việc làm sáng tỏ giáo lý và thực hiện những cải tổ lớn về đào tạo và kỷ luật.'},
 {year:'1962',title:'Công đồng Vaticanô II',era:'Hiện đại',body:'Vaticanô II canh tân đời sống Giáo Hội trong tương quan với Kinh Thánh, phụng vụ, đại kết và thế giới hiện đại.'},
 {year:'Hôm nay',title:'Một Giáo Hội Công giáo toàn cầu',era:'Đương đại',body:'Đời sống Công giáo hiện diện trong nhiều nền văn hóa và châu lục, được nối kết bằng phụng vụ, giáo huấn, ký ức và sứ mạng.'},
];

export default function TimelinePage(){return <main className={responsive.page} style={{background:'#f7f1e7',minHeight:'100vh',padding:'44px 0 80px'}}><div className="container">
 <div className="eyebrow">Lịch sử Giáo Hội · Bản đồ trực quan</div>
 <div className={responsive.hero} style={{display:'grid',gridTemplateColumns:'1.05fr .95fr',gap:28,alignItems:'center',marginTop:10}}><div><h1 className={responsive.title} style={{fontFamily:'Georgia,serif',fontSize:'clamp(48px,7vw,82px)',lineHeight:.95,margin:0,color:'#0b2848',letterSpacing:'-.04em'}}>Hai ngàn năm,<br/>được nối kết bằng hình ảnh.</h1><p className={responsive.lead} style={{fontFamily:'Georgia,serif',lineHeight:1.7,color:'#59656f',margin:'18px 0 0',maxWidth:760}}>Đi qua những bước ngoặt lớn của lịch sử, rồi từ mỗi biến cố mở sang con người, địa danh, văn kiện và giáo lý có liên hệ.</p></div><div className={responsive.heroMedia}><EditorialArtwork assetId="art.nicaea-icon" height={360} radius={22}/></div></div>
 <section style={{marginTop:28,background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:20,padding:'12px clamp(10px,2vw,28px)'}}><div className="eyebrow" style={{margin:'12px 0 0'}}>Trục lịch sử</div><MilestoneRibbon items={milestones.map(item=>({year:item.year,title:item.title,detail:item.era}))}/></section>
 <section className={responsive.timelineGrid} style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(310px,1fr))',gap:14,marginTop:16}}>{milestones.map((item,index)=><article className={responsive.timelineCard} key={item.year} style={{display:'grid',gridTemplateColumns:'88px 1fr',gap:18,background:'#fffaf1',border:'1px solid #dfd1ba',borderRadius:14,padding:18,boxShadow:'0 8px 24px rgba(48,35,18,.05)'}}><div><div style={{fontSize:10,textTransform:'uppercase',letterSpacing:'.08em',color:'#94631d',fontWeight:800}}>{item.era}</div><strong style={{display:'block',font:'30px Georgia,serif',color:'#0b2848',marginTop:6}}>{item.year}</strong><span style={{fontSize:10,color:'#8a7c68'}}>0{index+1}</span></div><div className={responsive.cardCopy}><h2 style={{font:'23px Georgia,serif',margin:'0 0 8px',color:'#122d4b'}}>{item.title}</h2><p style={{margin:0,color:'#59656f',lineHeight:1.65,fontFamily:'Georgia,serif',fontSize:14}}>{item.body}</p></div></article>)}</section>
 <section style={{marginTop:18,border:'1px solid #d8c9b0',borderRadius:14,background:'linear-gradient(135deg,#efe2ca,#fff8eb)',padding:22,display:'flex',justifyContent:'space-between',alignItems:'center',gap:20,flexWrap:'wrap'}}><div><div className="eyebrow">Câu chuyện có hướng dẫn</div><h2 style={{font:'30px Georgia,serif',margin:'8px 0',color:'#0b2848'}}>Bắt đầu từ Giáo Hội sơ khai.</h2><p style={{margin:0,color:'#59656f'}}>Theo bước Chúa Giêsu, các Tông đồ, thời bách hại, hoàng đế Constantinô và Công đồng Nixêa.</p></div><div className={responsive.actions}><Link className="btn btn-primary" href="/hanh-trinh/tu-chua-giesu-den-nixea">Bắt đầu hành trình →</Link></div></section>
 </div></main>}
